package com.xhhxd.retail.mapper.tm;

import com.xhhxd.retail.bean.tm.TmTeamMember;

public interface TmTeamMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_team_member
     *
     * @mbg.generated Mon Jun 04 10:18:19 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_team_member
     *
     * @mbg.generated Mon Jun 04 10:18:19 CST 2018
     */
    int insert(TmTeamMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_team_member
     *
     * @mbg.generated Mon Jun 04 10:18:19 CST 2018
     */
    int insertSelective(TmTeamMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_team_member
     *
     * @mbg.generated Mon Jun 04 10:18:19 CST 2018
     */
    TmTeamMember selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_team_member
     *
     * @mbg.generated Mon Jun 04 10:18:19 CST 2018
     */
    int updateByPrimaryKeySelective(TmTeamMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_team_member
     *
     * @mbg.generated Mon Jun 04 10:18:19 CST 2018
     */
    int updateByPrimaryKey(TmTeamMember record);
}