package com.shiwulian.wechat.mapper.bs;

import java.util.List;

import com.shiwulian.wechat.bean.bs.CustomerUser;

public interface CustomerUserMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_customer_user
	 * @mbg.generated  Mon Oct 16 10:46:44 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_customer_user
	 * @mbg.generated  Mon Oct 16 10:46:44 CST 2017
	 */
	int insert(CustomerUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_customer_user
	 * @mbg.generated  Mon Oct 16 10:46:44 CST 2017
	 */
	int insertSelective(CustomerUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_customer_user
	 * @mbg.generated  Mon Oct 16 10:46:44 CST 2017
	 */
	CustomerUser selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_customer_user
	 * @mbg.generated  Mon Oct 16 10:46:44 CST 2017
	 */
	int updateByPrimaryKeySelective(CustomerUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_customer_user
	 * @mbg.generated  Mon Oct 16 10:46:44 CST 2017
	 */
	int updateByPrimaryKey(CustomerUser record);

	CustomerUser selectByUid(String userId);    
    
    int deleteByUid(String userId);    
    
    List<CustomerUser> selectByCompanyId(String customerId);

	List<CustomerUser> selectByUserId(String userId);
	
	List<CustomerUser> selectByUids(List<String> userIds);
}