package com.shiwulian.wechat.mapper.bs;

import com.shiwulian.wechat.bean.bs.Customer;

public interface CustomerMapper {
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_customer
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_customer
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_customer
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_customer
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    Customer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_customer
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_customer
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    int updateByPrimaryKey(Customer record);
    /**
     * limit 1
     */
	Customer selectByName(String cnName);
}