package com.shiwulian.wechat.mapper.bs;

import com.shiwulian.wechat.bean.bs.Partner;


public interface PartnerMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_partner
	 * @mbg.generated  Thu Dec 21 16:59:42 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_partner
	 * @mbg.generated  Thu Dec 21 16:59:42 CST 2017
	 */
	int insert(Partner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_partner
	 * @mbg.generated  Thu Dec 21 16:59:42 CST 2017
	 */
	int insertSelective(Partner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_partner
	 * @mbg.generated  Thu Dec 21 16:59:42 CST 2017
	 */
	Partner selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_partner
	 * @mbg.generated  Thu Dec 21 16:59:42 CST 2017
	 */
	int updateByPrimaryKeySelective(Partner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_partner
	 * @mbg.generated  Thu Dec 21 16:59:42 CST 2017
	 */
	int updateByPrimaryKey(Partner record);
}