package com.shiwulian.wechat.mapper.bs;

import java.util.List;
import java.util.Map;

import com.shiwulian.wechat.bean.bs.User;

public interface UserMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	User selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	int updateByPrimaryKey(User record);

	User loginByMobile(String userName);
	
	User selectByUserName(String userName);
	
    User selectByMobile(String mobile);
    
    User selectByOpenid(String wechatOpenid);
    /**
     * 查询公司所有用户
     */
    List<User> colleagues(String customerId);
    
    int  updatePwd(Map<String, Object> map);
}