package com.xhhxd.retail.mapper.ac;

import com.xhhxd.retail.bean.ac.AcTeamAccount;

public interface AcTeamAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_team_account
     *
     * @mbg.generated Mon Jun 04 10:09:43 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_team_account
     *
     * @mbg.generated Mon Jun 04 10:09:43 CST 2018
     */
    int insert(AcTeamAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_team_account
     *
     * @mbg.generated Mon Jun 04 10:09:43 CST 2018
     */
    int insertSelective(AcTeamAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_team_account
     *
     * @mbg.generated Mon Jun 04 10:09:43 CST 2018
     */
    AcTeamAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_team_account
     *
     * @mbg.generated Mon Jun 04 10:09:43 CST 2018
     */
    int updateByPrimaryKeySelective(AcTeamAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_team_account
     *
     * @mbg.generated Mon Jun 04 10:09:43 CST 2018
     */
    int updateByPrimaryKey(AcTeamAccount record);
}