package com.shiwulian.wechat.bean.bs;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.id
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.code
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.cn_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String cnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.en_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String enName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.province_id
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private Integer provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.province_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.city_id
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.city_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.county_id
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private Integer countyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.county_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String countyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.cn_address
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String cnAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.en_address
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String enAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.fax
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.zip_code
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String zipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.reg_date
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private Date regDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.is_newlicense
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private Boolean isNewlicense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.license_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String licenseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.license_url
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String licenseUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.org_certificate_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String orgCertificateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.org_certificate_url
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String orgCertificateUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.tax_certificate_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String taxCertificateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.tax_certificate_url
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String taxCertificateUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.legal_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String legalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.ciq_code
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String ciqCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.partner_id
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String partnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.service_operator
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String serviceOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.approve_status
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private Boolean approveStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.approve_time
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private Date approveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.valid
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private Boolean valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.create_operator
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String createOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.create_time
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.upt_operator
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private String uptOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.upt_time
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private Date uptTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_customer.is_del
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.id
     *
     * @return the value of bs_customer.id
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.id
     *
     * @param id the value for bs_customer.id
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.code
     *
     * @return the value of bs_customer.code
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.code
     *
     * @param code the value for bs_customer.code
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.cn_name
     *
     * @return the value of bs_customer.cn_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getCnName() {
        return cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.cn_name
     *
     * @param cnName the value for bs_customer.cn_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setCnName(String cnName) {
        this.cnName = cnName == null ? null : cnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.en_name
     *
     * @return the value of bs_customer.en_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.en_name
     *
     * @param enName the value for bs_customer.en_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.province_id
     *
     * @return the value of bs_customer.province_id
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.province_id
     *
     * @param provinceId the value for bs_customer.province_id
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.province_name
     *
     * @return the value of bs_customer.province_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.province_name
     *
     * @param provinceName the value for bs_customer.province_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.city_id
     *
     * @return the value of bs_customer.city_id
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.city_id
     *
     * @param cityId the value for bs_customer.city_id
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.city_name
     *
     * @return the value of bs_customer.city_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.city_name
     *
     * @param cityName the value for bs_customer.city_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.county_id
     *
     * @return the value of bs_customer.county_id
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public Integer getCountyId() {
        return countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.county_id
     *
     * @param countyId the value for bs_customer.county_id
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setCountyId(Integer countyId) {
        this.countyId = countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.county_name
     *
     * @return the value of bs_customer.county_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getCountyName() {
        return countyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.county_name
     *
     * @param countyName the value for bs_customer.county_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setCountyName(String countyName) {
        this.countyName = countyName == null ? null : countyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.cn_address
     *
     * @return the value of bs_customer.cn_address
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getCnAddress() {
        return cnAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.cn_address
     *
     * @param cnAddress the value for bs_customer.cn_address
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setCnAddress(String cnAddress) {
        this.cnAddress = cnAddress == null ? null : cnAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.en_address
     *
     * @return the value of bs_customer.en_address
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getEnAddress() {
        return enAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.en_address
     *
     * @param enAddress the value for bs_customer.en_address
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setEnAddress(String enAddress) {
        this.enAddress = enAddress == null ? null : enAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.fax
     *
     * @return the value of bs_customer.fax
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.fax
     *
     * @param fax the value for bs_customer.fax
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.zip_code
     *
     * @return the value of bs_customer.zip_code
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.zip_code
     *
     * @param zipCode the value for bs_customer.zip_code
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.reg_date
     *
     * @return the value of bs_customer.reg_date
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.reg_date
     *
     * @param regDate the value for bs_customer.reg_date
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.is_newlicense
     *
     * @return the value of bs_customer.is_newlicense
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public Boolean getIsNewlicense() {
        return isNewlicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.is_newlicense
     *
     * @param isNewlicense the value for bs_customer.is_newlicense
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setIsNewlicense(Boolean isNewlicense) {
        this.isNewlicense = isNewlicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.license_name
     *
     * @return the value of bs_customer.license_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getLicenseName() {
        return licenseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.license_name
     *
     * @param licenseName the value for bs_customer.license_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setLicenseName(String licenseName) {
        this.licenseName = licenseName == null ? null : licenseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.license_url
     *
     * @return the value of bs_customer.license_url
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getLicenseUrl() {
        return licenseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.license_url
     *
     * @param licenseUrl the value for bs_customer.license_url
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setLicenseUrl(String licenseUrl) {
        this.licenseUrl = licenseUrl == null ? null : licenseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.org_certificate_name
     *
     * @return the value of bs_customer.org_certificate_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getOrgCertificateName() {
        return orgCertificateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.org_certificate_name
     *
     * @param orgCertificateName the value for bs_customer.org_certificate_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setOrgCertificateName(String orgCertificateName) {
        this.orgCertificateName = orgCertificateName == null ? null : orgCertificateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.org_certificate_url
     *
     * @return the value of bs_customer.org_certificate_url
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getOrgCertificateUrl() {
        return orgCertificateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.org_certificate_url
     *
     * @param orgCertificateUrl the value for bs_customer.org_certificate_url
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setOrgCertificateUrl(String orgCertificateUrl) {
        this.orgCertificateUrl = orgCertificateUrl == null ? null : orgCertificateUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.tax_certificate_name
     *
     * @return the value of bs_customer.tax_certificate_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getTaxCertificateName() {
        return taxCertificateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.tax_certificate_name
     *
     * @param taxCertificateName the value for bs_customer.tax_certificate_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setTaxCertificateName(String taxCertificateName) {
        this.taxCertificateName = taxCertificateName == null ? null : taxCertificateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.tax_certificate_url
     *
     * @return the value of bs_customer.tax_certificate_url
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getTaxCertificateUrl() {
        return taxCertificateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.tax_certificate_url
     *
     * @param taxCertificateUrl the value for bs_customer.tax_certificate_url
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setTaxCertificateUrl(String taxCertificateUrl) {
        this.taxCertificateUrl = taxCertificateUrl == null ? null : taxCertificateUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.legal_name
     *
     * @return the value of bs_customer.legal_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getLegalName() {
        return legalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.legal_name
     *
     * @param legalName the value for bs_customer.legal_name
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setLegalName(String legalName) {
        this.legalName = legalName == null ? null : legalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.ciq_code
     *
     * @return the value of bs_customer.ciq_code
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getCiqCode() {
        return ciqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.ciq_code
     *
     * @param ciqCode the value for bs_customer.ciq_code
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setCiqCode(String ciqCode) {
        this.ciqCode = ciqCode == null ? null : ciqCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.partner_id
     *
     * @return the value of bs_customer.partner_id
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.partner_id
     *
     * @param partnerId the value for bs_customer.partner_id
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId == null ? null : partnerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.service_operator
     *
     * @return the value of bs_customer.service_operator
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getServiceOperator() {
        return serviceOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.service_operator
     *
     * @param serviceOperator the value for bs_customer.service_operator
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setServiceOperator(String serviceOperator) {
        this.serviceOperator = serviceOperator == null ? null : serviceOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.approve_status
     *
     * @return the value of bs_customer.approve_status
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public Boolean getApproveStatus() {
        return approveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.approve_status
     *
     * @param approveStatus the value for bs_customer.approve_status
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setApproveStatus(Boolean approveStatus) {
        this.approveStatus = approveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.approve_time
     *
     * @return the value of bs_customer.approve_time
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public Date getApproveTime() {
        return approveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.approve_time
     *
     * @param approveTime the value for bs_customer.approve_time
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setApproveTime(Date approveTime) {
        this.approveTime = approveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.valid
     *
     * @return the value of bs_customer.valid
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.valid
     *
     * @param valid the value for bs_customer.valid
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.create_operator
     *
     * @return the value of bs_customer.create_operator
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getCreateOperator() {
        return createOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.create_operator
     *
     * @param createOperator the value for bs_customer.create_operator
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setCreateOperator(String createOperator) {
        this.createOperator = createOperator == null ? null : createOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.create_time
     *
     * @return the value of bs_customer.create_time
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.create_time
     *
     * @param createTime the value for bs_customer.create_time
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.upt_operator
     *
     * @return the value of bs_customer.upt_operator
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public String getUptOperator() {
        return uptOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.upt_operator
     *
     * @param uptOperator the value for bs_customer.upt_operator
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setUptOperator(String uptOperator) {
        this.uptOperator = uptOperator == null ? null : uptOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.upt_time
     *
     * @return the value of bs_customer.upt_time
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public Date getUptTime() {
        return uptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.upt_time
     *
     * @param uptTime the value for bs_customer.upt_time
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setUptTime(Date uptTime) {
        this.uptTime = uptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_customer.is_del
     *
     * @return the value of bs_customer.is_del
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_customer.is_del
     *
     * @param isDel the value for bs_customer.is_del
     *
     * @mbg.generated Tue Jan 02 14:13:50 CST 2018
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}