package com.shiwulian.wechat.bean.bs;

import java.math.BigDecimal;
import java.util.Date;

public class ProductTariff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_product_tariff.hs_code
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    private String hsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_product_tariff.hs_name
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    private String hsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_product_tariff.is_from_weight
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    private Boolean isFromWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_product_tariff.tariff_rate
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    private BigDecimal tariffRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_product_tariff.vat_rate
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    private BigDecimal vatRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_product_tariff.main_unit_id
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    private Integer mainUnitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_product_tariff.next_unit_id
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    private Integer nextUnitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_product_tariff.tariff_type_code
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    private String tariffTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_product_tariff.valid
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    private Boolean valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_product_tariff.create_operator
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    private String createOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_product_tariff.create_time
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_product_tariff.upt_operator
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    private String uptOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_product_tariff.upt_time
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    private Date uptTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_product_tariff.is_del
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_product_tariff.hs_code
     *
     * @return the value of bs_product_tariff.hs_code
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public String getHsCode() {
        return hsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_product_tariff.hs_code
     *
     * @param hsCode the value for bs_product_tariff.hs_code
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public void setHsCode(String hsCode) {
        this.hsCode = hsCode == null ? null : hsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_product_tariff.hs_name
     *
     * @return the value of bs_product_tariff.hs_name
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public String getHsName() {
        return hsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_product_tariff.hs_name
     *
     * @param hsName the value for bs_product_tariff.hs_name
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public void setHsName(String hsName) {
        this.hsName = hsName == null ? null : hsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_product_tariff.is_from_weight
     *
     * @return the value of bs_product_tariff.is_from_weight
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public Boolean getIsFromWeight() {
        return isFromWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_product_tariff.is_from_weight
     *
     * @param isFromWeight the value for bs_product_tariff.is_from_weight
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public void setIsFromWeight(Boolean isFromWeight) {
        this.isFromWeight = isFromWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_product_tariff.tariff_rate
     *
     * @return the value of bs_product_tariff.tariff_rate
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public BigDecimal getTariffRate() {
        return tariffRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_product_tariff.tariff_rate
     *
     * @param tariffRate the value for bs_product_tariff.tariff_rate
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public void setTariffRate(BigDecimal tariffRate) {
        this.tariffRate = tariffRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_product_tariff.vat_rate
     *
     * @return the value of bs_product_tariff.vat_rate
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public BigDecimal getVatRate() {
        return vatRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_product_tariff.vat_rate
     *
     * @param vatRate the value for bs_product_tariff.vat_rate
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public void setVatRate(BigDecimal vatRate) {
        this.vatRate = vatRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_product_tariff.main_unit_id
     *
     * @return the value of bs_product_tariff.main_unit_id
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public Integer getMainUnitId() {
        return mainUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_product_tariff.main_unit_id
     *
     * @param mainUnitId the value for bs_product_tariff.main_unit_id
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public void setMainUnitId(Integer mainUnitId) {
        this.mainUnitId = mainUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_product_tariff.next_unit_id
     *
     * @return the value of bs_product_tariff.next_unit_id
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public Integer getNextUnitId() {
        return nextUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_product_tariff.next_unit_id
     *
     * @param nextUnitId the value for bs_product_tariff.next_unit_id
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public void setNextUnitId(Integer nextUnitId) {
        this.nextUnitId = nextUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_product_tariff.tariff_type_code
     *
     * @return the value of bs_product_tariff.tariff_type_code
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public String getTariffTypeCode() {
        return tariffTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_product_tariff.tariff_type_code
     *
     * @param tariffTypeCode the value for bs_product_tariff.tariff_type_code
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public void setTariffTypeCode(String tariffTypeCode) {
        this.tariffTypeCode = tariffTypeCode == null ? null : tariffTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_product_tariff.valid
     *
     * @return the value of bs_product_tariff.valid
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_product_tariff.valid
     *
     * @param valid the value for bs_product_tariff.valid
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_product_tariff.create_operator
     *
     * @return the value of bs_product_tariff.create_operator
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public String getCreateOperator() {
        return createOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_product_tariff.create_operator
     *
     * @param createOperator the value for bs_product_tariff.create_operator
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public void setCreateOperator(String createOperator) {
        this.createOperator = createOperator == null ? null : createOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_product_tariff.create_time
     *
     * @return the value of bs_product_tariff.create_time
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_product_tariff.create_time
     *
     * @param createTime the value for bs_product_tariff.create_time
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_product_tariff.upt_operator
     *
     * @return the value of bs_product_tariff.upt_operator
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public String getUptOperator() {
        return uptOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_product_tariff.upt_operator
     *
     * @param uptOperator the value for bs_product_tariff.upt_operator
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public void setUptOperator(String uptOperator) {
        this.uptOperator = uptOperator == null ? null : uptOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_product_tariff.upt_time
     *
     * @return the value of bs_product_tariff.upt_time
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public Date getUptTime() {
        return uptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_product_tariff.upt_time
     *
     * @param uptTime the value for bs_product_tariff.upt_time
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public void setUptTime(Date uptTime) {
        this.uptTime = uptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_product_tariff.is_del
     *
     * @return the value of bs_product_tariff.is_del
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_product_tariff.is_del
     *
     * @param isDel the value for bs_product_tariff.is_del
     *
     * @mbg.generated Tue Oct 10 10:49:00 CST 2017
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}