package com.shiwulian.wechat.bean.bs;

import java.util.Date;

public class Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.id
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.en_name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private String enName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.category_id
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private Integer categoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.category_name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private String categoryName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.country_id
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private Integer countryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.country_name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private String countryName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.main_unit_id
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private Integer mainUnitId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.main_unit_name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private String mainUnitName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.next_unit_id
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private Integer nextUnitId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.next_unit_name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private String nextUnitName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.hs_code
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private String hsCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.pic_url
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private String picUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.valid
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private Boolean valid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.create_operator
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private String createOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.create_time
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.upt_operator
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private String uptOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.upt_time
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private Date uptTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.is_del
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private Boolean isDel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_product.is_hx
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	private Boolean isHx;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.id
	 * @return  the value of bs_product.id
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.id
	 * @param id  the value for bs_product.id
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.name
	 * @return  the value of bs_product.name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.name
	 * @param name  the value for bs_product.name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.en_name
	 * @return  the value of bs_product.en_name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public String getEnName() {
		return enName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.en_name
	 * @param enName  the value for bs_product.en_name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setEnName(String enName) {
		this.enName = enName == null ? null : enName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.category_id
	 * @return  the value of bs_product.category_id
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.category_id
	 * @param categoryId  the value for bs_product.category_id
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.category_name
	 * @return  the value of bs_product.category_name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public String getCategoryName() {
		return categoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.category_name
	 * @param categoryName  the value for bs_product.category_name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName == null ? null : categoryName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.country_id
	 * @return  the value of bs_product.country_id
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public Integer getCountryId() {
		return countryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.country_id
	 * @param countryId  the value for bs_product.country_id
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.country_name
	 * @return  the value of bs_product.country_name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public String getCountryName() {
		return countryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.country_name
	 * @param countryName  the value for bs_product.country_name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setCountryName(String countryName) {
		this.countryName = countryName == null ? null : countryName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.main_unit_id
	 * @return  the value of bs_product.main_unit_id
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public Integer getMainUnitId() {
		return mainUnitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.main_unit_id
	 * @param mainUnitId  the value for bs_product.main_unit_id
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setMainUnitId(Integer mainUnitId) {
		this.mainUnitId = mainUnitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.main_unit_name
	 * @return  the value of bs_product.main_unit_name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public String getMainUnitName() {
		return mainUnitName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.main_unit_name
	 * @param mainUnitName  the value for bs_product.main_unit_name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setMainUnitName(String mainUnitName) {
		this.mainUnitName = mainUnitName == null ? null : mainUnitName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.next_unit_id
	 * @return  the value of bs_product.next_unit_id
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public Integer getNextUnitId() {
		return nextUnitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.next_unit_id
	 * @param nextUnitId  the value for bs_product.next_unit_id
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setNextUnitId(Integer nextUnitId) {
		this.nextUnitId = nextUnitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.next_unit_name
	 * @return  the value of bs_product.next_unit_name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public String getNextUnitName() {
		return nextUnitName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.next_unit_name
	 * @param nextUnitName  the value for bs_product.next_unit_name
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setNextUnitName(String nextUnitName) {
		this.nextUnitName = nextUnitName == null ? null : nextUnitName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.hs_code
	 * @return  the value of bs_product.hs_code
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public String getHsCode() {
		return hsCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.hs_code
	 * @param hsCode  the value for bs_product.hs_code
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setHsCode(String hsCode) {
		this.hsCode = hsCode == null ? null : hsCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.pic_url
	 * @return  the value of bs_product.pic_url
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public String getPicUrl() {
		return picUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.pic_url
	 * @param picUrl  the value for bs_product.pic_url
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl == null ? null : picUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.valid
	 * @return  the value of bs_product.valid
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public Boolean getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.valid
	 * @param valid  the value for bs_product.valid
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.create_operator
	 * @return  the value of bs_product.create_operator
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public String getCreateOperator() {
		return createOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.create_operator
	 * @param createOperator  the value for bs_product.create_operator
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setCreateOperator(String createOperator) {
		this.createOperator = createOperator == null ? null : createOperator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.create_time
	 * @return  the value of bs_product.create_time
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.create_time
	 * @param createTime  the value for bs_product.create_time
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.upt_operator
	 * @return  the value of bs_product.upt_operator
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public String getUptOperator() {
		return uptOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.upt_operator
	 * @param uptOperator  the value for bs_product.upt_operator
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setUptOperator(String uptOperator) {
		this.uptOperator = uptOperator == null ? null : uptOperator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.upt_time
	 * @return  the value of bs_product.upt_time
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public Date getUptTime() {
		return uptTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.upt_time
	 * @param uptTime  the value for bs_product.upt_time
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setUptTime(Date uptTime) {
		this.uptTime = uptTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.is_del
	 * @return  the value of bs_product.is_del
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public Boolean getIsDel() {
		return isDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.is_del
	 * @param isDel  the value for bs_product.is_del
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setIsDel(Boolean isDel) {
		this.isDel = isDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_product.is_hx
	 * @return  the value of bs_product.is_hx
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public Boolean getIsHx() {
		return isHx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_product.is_hx
	 * @param isHx  the value for bs_product.is_hx
	 * @mbg.generated  Mon Dec 04 18:57:33 CST 2017
	 */
	public void setIsHx(Boolean isHx) {
		this.isHx = isHx;
	}
}