package com.shiwulian.wechat.bean.bs;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.id
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.user_name
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.real_name
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private String realName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.portrait
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private String portrait;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.gender
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private Boolean gender;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.english_name
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private String englishName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.mobile
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private String mobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.password
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.email
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.weixin_code
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private String weixinCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.birthday
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private Date birthday;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.verify_mobile
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private Boolean verifyMobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.verify_email
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private Boolean verifyEmail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.user_type
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private Integer userType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.wechat_openid
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private String wechatOpenid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.wechat_bindtime
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private Date wechatBindtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.valid
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private Boolean valid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.create_operator
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private String createOperator;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.create_time
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.upt_operator
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private String uptOperator;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.upt_time
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private Date uptTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.is_del
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	private Boolean isDel;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.id
	 * @return  the value of bs_user.id
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.id
	 * @param id  the value for bs_user.id
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.user_name
	 * @return  the value of bs_user.user_name
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.user_name
	 * @param userName  the value for bs_user.user_name
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.real_name
	 * @return  the value of bs_user.real_name
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.real_name
	 * @param realName  the value for bs_user.real_name
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setRealName(String realName) {
		this.realName = realName == null ? null : realName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.portrait
	 * @return  the value of bs_user.portrait
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public String getPortrait() {
		return portrait;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.portrait
	 * @param portrait  the value for bs_user.portrait
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setPortrait(String portrait) {
		this.portrait = portrait == null ? null : portrait.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.gender
	 * @return  the value of bs_user.gender
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public Boolean getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.gender
	 * @param gender  the value for bs_user.gender
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setGender(Boolean gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.english_name
	 * @return  the value of bs_user.english_name
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public String getEnglishName() {
		return englishName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.english_name
	 * @param englishName  the value for bs_user.english_name
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setEnglishName(String englishName) {
		this.englishName = englishName == null ? null : englishName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.mobile
	 * @return  the value of bs_user.mobile
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.mobile
	 * @param mobile  the value for bs_user.mobile
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.password
	 * @return  the value of bs_user.password
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.password
	 * @param password  the value for bs_user.password
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.email
	 * @return  the value of bs_user.email
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.email
	 * @param email  the value for bs_user.email
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.weixin_code
	 * @return  the value of bs_user.weixin_code
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public String getWeixinCode() {
		return weixinCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.weixin_code
	 * @param weixinCode  the value for bs_user.weixin_code
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setWeixinCode(String weixinCode) {
		this.weixinCode = weixinCode == null ? null : weixinCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.birthday
	 * @return  the value of bs_user.birthday
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.birthday
	 * @param birthday  the value for bs_user.birthday
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.verify_mobile
	 * @return  the value of bs_user.verify_mobile
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public Boolean getVerifyMobile() {
		return verifyMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.verify_mobile
	 * @param verifyMobile  the value for bs_user.verify_mobile
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setVerifyMobile(Boolean verifyMobile) {
		this.verifyMobile = verifyMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.verify_email
	 * @return  the value of bs_user.verify_email
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public Boolean getVerifyEmail() {
		return verifyEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.verify_email
	 * @param verifyEmail  the value for bs_user.verify_email
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setVerifyEmail(Boolean verifyEmail) {
		this.verifyEmail = verifyEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.user_type
	 * @return  the value of bs_user.user_type
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public Integer getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.user_type
	 * @param userType  the value for bs_user.user_type
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.wechat_openid
	 * @return  the value of bs_user.wechat_openid
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public String getWechatOpenid() {
		return wechatOpenid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.wechat_openid
	 * @param wechatOpenid  the value for bs_user.wechat_openid
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setWechatOpenid(String wechatOpenid) {
		this.wechatOpenid = wechatOpenid == null ? null : wechatOpenid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.wechat_bindtime
	 * @return  the value of bs_user.wechat_bindtime
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public Date getWechatBindtime() {
		return wechatBindtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.wechat_bindtime
	 * @param wechatBindtime  the value for bs_user.wechat_bindtime
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setWechatBindtime(Date wechatBindtime) {
		this.wechatBindtime = wechatBindtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.valid
	 * @return  the value of bs_user.valid
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public Boolean getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.valid
	 * @param valid  the value for bs_user.valid
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.create_operator
	 * @return  the value of bs_user.create_operator
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public String getCreateOperator() {
		return createOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.create_operator
	 * @param createOperator  the value for bs_user.create_operator
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setCreateOperator(String createOperator) {
		this.createOperator = createOperator == null ? null : createOperator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.create_time
	 * @return  the value of bs_user.create_time
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.create_time
	 * @param createTime  the value for bs_user.create_time
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.upt_operator
	 * @return  the value of bs_user.upt_operator
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public String getUptOperator() {
		return uptOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.upt_operator
	 * @param uptOperator  the value for bs_user.upt_operator
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setUptOperator(String uptOperator) {
		this.uptOperator = uptOperator == null ? null : uptOperator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.upt_time
	 * @return  the value of bs_user.upt_time
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public Date getUptTime() {
		return uptTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.upt_time
	 * @param uptTime  the value for bs_user.upt_time
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setUptTime(Date uptTime) {
		this.uptTime = uptTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.is_del
	 * @return  the value of bs_user.is_del
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public Boolean getIsDel() {
		return isDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.is_del
	 * @param isDel  the value for bs_user.is_del
	 * @mbg.generated  Fri Dec 29 10:30:56 CST 2017
	 */
	public void setIsDel(Boolean isDel) {
		this.isDel = isDel;
	}

	private final static long serialVersionUID = -1517522427632942606L;

	/**
	 * 拍档或�?�客户（根据用户类型取�?�）
	 */
	private String customerId;
	
	private Integer customerType;

	/**
	 * 拍档id或�?�客户id（根据用户类型取值）
	 */
	public String getCustomerId() {
		return customerId;
	}

	/**
	 * 拍档id或�?�客户id（根据用户类型取值）
	 */
	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public Integer getCustomerType() {
		return customerType;
	}

	public void setCustomerType(Integer customerType) {
		this.customerType = customerType;
	}	
}