package com.xhhxd.retail.mapper.bs;

import com.xhhxd.retail.bean.bs.BsSupplier;

public interface BsSupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_supplier
     *
     * @mbg.generated Mon Jun 04 10:11:48 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_supplier
     *
     * @mbg.generated Mon Jun 04 10:11:48 CST 2018
     */
    int insert(BsSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_supplier
     *
     * @mbg.generated Mon Jun 04 10:11:48 CST 2018
     */
    int insertSelective(BsSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_supplier
     *
     * @mbg.generated Mon Jun 04 10:11:48 CST 2018
     */
    BsSupplier selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_supplier
     *
     * @mbg.generated Mon Jun 04 10:11:48 CST 2018
     */
    int updateByPrimaryKeySelective(BsSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_supplier
     *
     * @mbg.generated Mon Jun 04 10:11:48 CST 2018
     */
    int updateByPrimaryKey(BsSupplier record);
}