package com.xhhxd.retail.mapper.bs;

import com.xhhxd.retail.bean.bs.BsTeam;

public interface BsTeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_team
     *
     * @mbg.generated Mon Jun 04 10:11:48 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_team
     *
     * @mbg.generated Mon Jun 04 10:11:48 CST 2018
     */
    int insert(BsTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_team
     *
     * @mbg.generated Mon Jun 04 10:11:48 CST 2018
     */
    int insertSelective(BsTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_team
     *
     * @mbg.generated Mon Jun 04 10:11:48 CST 2018
     */
    BsTeam selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_team
     *
     * @mbg.generated Mon Jun 04 10:11:48 CST 2018
     */
    int updateByPrimaryKeySelective(BsTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_team
     *
     * @mbg.generated Mon Jun 04 10:11:48 CST 2018
     */
    int updateByPrimaryKey(BsTeam record);
}