package com.shiwulian.wechat.bean.od;

import java.math.BigDecimal;
import java.util.Date;

public class OrderFinancial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.order_id
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.financing_type
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private Integer financingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.financing_days
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private Integer financingDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.financing_percent
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private Integer financingPercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.financing_amount
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private BigDecimal financingAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.financing_remark
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private String financingRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.financing_limit_amount
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private BigDecimal financingLimitAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.status
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.create_operator
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private String createOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.create_time
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.upt_operator
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private String uptOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.upt_time
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private Date uptTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.is_del
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private Boolean isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.risk_price_rate
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private Integer riskPriceRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.risk_amount_rate
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private Integer riskAmountRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.pay_amount
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private BigDecimal payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.pay_preback_date
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private Date payPrebackDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.pay_memo
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private String payMemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.pay_status
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private Integer payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.pay_apply_time
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private Date payApplyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.pay_apply_operator
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private String payApplyOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.pay_outbank_id
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private String payOutbankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.pay_inbank_id
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private String payInbankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.pay_date
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private Date payDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_financial.pay_operator
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    private String payOperator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.order_id
     *
     * @return the value of od_order_financial.order_id
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.order_id
     *
     * @param orderId the value for od_order_financial.order_id
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.financing_type
     *
     * @return the value of od_order_financial.financing_type
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public Integer getFinancingType() {
        return financingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.financing_type
     *
     * @param financingType the value for od_order_financial.financing_type
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setFinancingType(Integer financingType) {
        this.financingType = financingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.financing_days
     *
     * @return the value of od_order_financial.financing_days
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public Integer getFinancingDays() {
        return financingDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.financing_days
     *
     * @param financingDays the value for od_order_financial.financing_days
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setFinancingDays(Integer financingDays) {
        this.financingDays = financingDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.financing_percent
     *
     * @return the value of od_order_financial.financing_percent
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public Integer getFinancingPercent() {
        return financingPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.financing_percent
     *
     * @param financingPercent the value for od_order_financial.financing_percent
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setFinancingPercent(Integer financingPercent) {
        this.financingPercent = financingPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.financing_amount
     *
     * @return the value of od_order_financial.financing_amount
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public BigDecimal getFinancingAmount() {
        return financingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.financing_amount
     *
     * @param financingAmount the value for od_order_financial.financing_amount
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setFinancingAmount(BigDecimal financingAmount) {
        this.financingAmount = financingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.financing_remark
     *
     * @return the value of od_order_financial.financing_remark
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public String getFinancingRemark() {
        return financingRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.financing_remark
     *
     * @param financingRemark the value for od_order_financial.financing_remark
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setFinancingRemark(String financingRemark) {
        this.financingRemark = financingRemark == null ? null : financingRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.financing_limit_amount
     *
     * @return the value of od_order_financial.financing_limit_amount
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public BigDecimal getFinancingLimitAmount() {
        return financingLimitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.financing_limit_amount
     *
     * @param financingLimitAmount the value for od_order_financial.financing_limit_amount
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setFinancingLimitAmount(BigDecimal financingLimitAmount) {
        this.financingLimitAmount = financingLimitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.status
     *
     * @return the value of od_order_financial.status
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.status
     *
     * @param status the value for od_order_financial.status
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.create_operator
     *
     * @return the value of od_order_financial.create_operator
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public String getCreateOperator() {
        return createOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.create_operator
     *
     * @param createOperator the value for od_order_financial.create_operator
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setCreateOperator(String createOperator) {
        this.createOperator = createOperator == null ? null : createOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.create_time
     *
     * @return the value of od_order_financial.create_time
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.create_time
     *
     * @param createTime the value for od_order_financial.create_time
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.upt_operator
     *
     * @return the value of od_order_financial.upt_operator
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public String getUptOperator() {
        return uptOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.upt_operator
     *
     * @param uptOperator the value for od_order_financial.upt_operator
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setUptOperator(String uptOperator) {
        this.uptOperator = uptOperator == null ? null : uptOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.upt_time
     *
     * @return the value of od_order_financial.upt_time
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public Date getUptTime() {
        return uptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.upt_time
     *
     * @param uptTime the value for od_order_financial.upt_time
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setUptTime(Date uptTime) {
        this.uptTime = uptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.is_del
     *
     * @return the value of od_order_financial.is_del
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.is_del
     *
     * @param isDel the value for od_order_financial.is_del
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.risk_price_rate
     *
     * @return the value of od_order_financial.risk_price_rate
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public Integer getRiskPriceRate() {
        return riskPriceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.risk_price_rate
     *
     * @param riskPriceRate the value for od_order_financial.risk_price_rate
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setRiskPriceRate(Integer riskPriceRate) {
        this.riskPriceRate = riskPriceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.risk_amount_rate
     *
     * @return the value of od_order_financial.risk_amount_rate
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public Integer getRiskAmountRate() {
        return riskAmountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.risk_amount_rate
     *
     * @param riskAmountRate the value for od_order_financial.risk_amount_rate
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setRiskAmountRate(Integer riskAmountRate) {
        this.riskAmountRate = riskAmountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.pay_amount
     *
     * @return the value of od_order_financial.pay_amount
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.pay_amount
     *
     * @param payAmount the value for od_order_financial.pay_amount
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.pay_preback_date
     *
     * @return the value of od_order_financial.pay_preback_date
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public Date getPayPrebackDate() {
        return payPrebackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.pay_preback_date
     *
     * @param payPrebackDate the value for od_order_financial.pay_preback_date
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setPayPrebackDate(Date payPrebackDate) {
        this.payPrebackDate = payPrebackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.pay_memo
     *
     * @return the value of od_order_financial.pay_memo
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public String getPayMemo() {
        return payMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.pay_memo
     *
     * @param payMemo the value for od_order_financial.pay_memo
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setPayMemo(String payMemo) {
        this.payMemo = payMemo == null ? null : payMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.pay_status
     *
     * @return the value of od_order_financial.pay_status
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.pay_status
     *
     * @param payStatus the value for od_order_financial.pay_status
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.pay_apply_time
     *
     * @return the value of od_order_financial.pay_apply_time
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public Date getPayApplyTime() {
        return payApplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.pay_apply_time
     *
     * @param payApplyTime the value for od_order_financial.pay_apply_time
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setPayApplyTime(Date payApplyTime) {
        this.payApplyTime = payApplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.pay_apply_operator
     *
     * @return the value of od_order_financial.pay_apply_operator
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public String getPayApplyOperator() {
        return payApplyOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.pay_apply_operator
     *
     * @param payApplyOperator the value for od_order_financial.pay_apply_operator
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setPayApplyOperator(String payApplyOperator) {
        this.payApplyOperator = payApplyOperator == null ? null : payApplyOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.pay_outbank_id
     *
     * @return the value of od_order_financial.pay_outbank_id
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public String getPayOutbankId() {
        return payOutbankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.pay_outbank_id
     *
     * @param payOutbankId the value for od_order_financial.pay_outbank_id
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setPayOutbankId(String payOutbankId) {
        this.payOutbankId = payOutbankId == null ? null : payOutbankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.pay_inbank_id
     *
     * @return the value of od_order_financial.pay_inbank_id
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public String getPayInbankId() {
        return payInbankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.pay_inbank_id
     *
     * @param payInbankId the value for od_order_financial.pay_inbank_id
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setPayInbankId(String payInbankId) {
        this.payInbankId = payInbankId == null ? null : payInbankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.pay_date
     *
     * @return the value of od_order_financial.pay_date
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.pay_date
     *
     * @param payDate the value for od_order_financial.pay_date
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_financial.pay_operator
     *
     * @return the value of od_order_financial.pay_operator
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public String getPayOperator() {
        return payOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_financial.pay_operator
     *
     * @param payOperator the value for od_order_financial.pay_operator
     *
     * @mbg.generated Wed Jan 03 13:19:35 CST 2018
     */
    public void setPayOperator(String payOperator) {
        this.payOperator = payOperator == null ? null : payOperator.trim();
    }
}