package com.shiwulian.wechat.bean.od;

import java.util.Date;

public class OrderDocument {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_document.id
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_document.order_id
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_document.bill_id
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    private Integer billId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_document.bill_file_url
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    private String billFileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_document.bill_file_name
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    private String billFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_document.bill_no
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    private String billNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_document.status
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_document.upload_operator
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    private String uploadOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_document.upload_time
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    private Date uploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_document.create_operator
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    private String createOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_document.create_time
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_document.upt_operator
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    private String uptOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_document.upt_time
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    private Date uptTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_document.is_del
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_document.id
     *
     * @return the value of od_order_document.id
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_document.id
     *
     * @param id the value for od_order_document.id
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_document.order_id
     *
     * @return the value of od_order_document.order_id
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_document.order_id
     *
     * @param orderId the value for od_order_document.order_id
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_document.bill_id
     *
     * @return the value of od_order_document.bill_id
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public Integer getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_document.bill_id
     *
     * @param billId the value for od_order_document.bill_id
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public void setBillId(Integer billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_document.bill_file_url
     *
     * @return the value of od_order_document.bill_file_url
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public String getBillFileUrl() {
        return billFileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_document.bill_file_url
     *
     * @param billFileUrl the value for od_order_document.bill_file_url
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public void setBillFileUrl(String billFileUrl) {
        this.billFileUrl = billFileUrl == null ? null : billFileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_document.bill_file_name
     *
     * @return the value of od_order_document.bill_file_name
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public String getBillFileName() {
        return billFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_document.bill_file_name
     *
     * @param billFileName the value for od_order_document.bill_file_name
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public void setBillFileName(String billFileName) {
        this.billFileName = billFileName == null ? null : billFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_document.bill_no
     *
     * @return the value of od_order_document.bill_no
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_document.bill_no
     *
     * @param billNo the value for od_order_document.bill_no
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo == null ? null : billNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_document.status
     *
     * @return the value of od_order_document.status
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_document.status
     *
     * @param status the value for od_order_document.status
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_document.upload_operator
     *
     * @return the value of od_order_document.upload_operator
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public String getUploadOperator() {
        return uploadOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_document.upload_operator
     *
     * @param uploadOperator the value for od_order_document.upload_operator
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public void setUploadOperator(String uploadOperator) {
        this.uploadOperator = uploadOperator == null ? null : uploadOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_document.upload_time
     *
     * @return the value of od_order_document.upload_time
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_document.upload_time
     *
     * @param uploadTime the value for od_order_document.upload_time
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_document.create_operator
     *
     * @return the value of od_order_document.create_operator
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public String getCreateOperator() {
        return createOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_document.create_operator
     *
     * @param createOperator the value for od_order_document.create_operator
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public void setCreateOperator(String createOperator) {
        this.createOperator = createOperator == null ? null : createOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_document.create_time
     *
     * @return the value of od_order_document.create_time
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_document.create_time
     *
     * @param createTime the value for od_order_document.create_time
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_document.upt_operator
     *
     * @return the value of od_order_document.upt_operator
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public String getUptOperator() {
        return uptOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_document.upt_operator
     *
     * @param uptOperator the value for od_order_document.upt_operator
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public void setUptOperator(String uptOperator) {
        this.uptOperator = uptOperator == null ? null : uptOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_document.upt_time
     *
     * @return the value of od_order_document.upt_time
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public Date getUptTime() {
        return uptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_document.upt_time
     *
     * @param uptTime the value for od_order_document.upt_time
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public void setUptTime(Date uptTime) {
        this.uptTime = uptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_document.is_del
     *
     * @return the value of od_order_document.is_del
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_document.is_del
     *
     * @param isDel the value for od_order_document.is_del
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

}