package com.shiwulian.wechat.bean.od;

import java.util.Date;

public class OrderTradeCustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_customer.id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_customer.trade_id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private String tradeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_customer.order_id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_customer.cucustomer_id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private String cucustomerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_customer.cucontact_id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private String cucontactId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_customer.create_operator
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private String createOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_customer.create_time
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_customer.upt_operator
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private String uptOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_customer.upt_time
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private Date uptTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_customer.is_del
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_customer.id
     *
     * @return the value of od_order_trade_customer.id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_customer.id
     *
     * @param id the value for od_order_trade_customer.id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_customer.trade_id
     *
     * @return the value of od_order_trade_customer.trade_id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public String getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_customer.trade_id
     *
     * @param tradeId the value for od_order_trade_customer.trade_id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setTradeId(String tradeId) {
        this.tradeId = tradeId == null ? null : tradeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_customer.order_id
     *
     * @return the value of od_order_trade_customer.order_id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_customer.order_id
     *
     * @param orderId the value for od_order_trade_customer.order_id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_customer.cucustomer_id
     *
     * @return the value of od_order_trade_customer.cucustomer_id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public String getCucustomerId() {
        return cucustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_customer.cucustomer_id
     *
     * @param cucustomerId the value for od_order_trade_customer.cucustomer_id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setCucustomerId(String cucustomerId) {
        this.cucustomerId = cucustomerId == null ? null : cucustomerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_customer.cucontact_id
     *
     * @return the value of od_order_trade_customer.cucontact_id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public String getCucontactId() {
        return cucontactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_customer.cucontact_id
     *
     * @param cucontactId the value for od_order_trade_customer.cucontact_id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setCucontactId(String cucontactId) {
        this.cucontactId = cucontactId == null ? null : cucontactId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_customer.create_operator
     *
     * @return the value of od_order_trade_customer.create_operator
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public String getCreateOperator() {
        return createOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_customer.create_operator
     *
     * @param createOperator the value for od_order_trade_customer.create_operator
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setCreateOperator(String createOperator) {
        this.createOperator = createOperator == null ? null : createOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_customer.create_time
     *
     * @return the value of od_order_trade_customer.create_time
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_customer.create_time
     *
     * @param createTime the value for od_order_trade_customer.create_time
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_customer.upt_operator
     *
     * @return the value of od_order_trade_customer.upt_operator
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public String getUptOperator() {
        return uptOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_customer.upt_operator
     *
     * @param uptOperator the value for od_order_trade_customer.upt_operator
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setUptOperator(String uptOperator) {
        this.uptOperator = uptOperator == null ? null : uptOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_customer.upt_time
     *
     * @return the value of od_order_trade_customer.upt_time
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public Date getUptTime() {
        return uptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_customer.upt_time
     *
     * @param uptTime the value for od_order_trade_customer.upt_time
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setUptTime(Date uptTime) {
        this.uptTime = uptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_customer.is_del
     *
     * @return the value of od_order_trade_customer.is_del
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_customer.is_del
     *
     * @param isDel the value for od_order_trade_customer.is_del
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}