package com.shiwulian.wechat.bean.od;

import java.math.BigDecimal;
import java.util.Date;

public class OrderTradeItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.order_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.trade_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private String tradeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.category_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.category_name
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.country_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private Integer countryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.country_name
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private String countryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.product_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.stproduct_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private String stproductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.product_name
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.en_name
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private String enName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.hs_code
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private String hsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.product_spec
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private String productSpec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.product_amount
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private BigDecimal productAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.product_unit_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private Integer productUnitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.product_sale_price
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private BigDecimal productSalePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.product_total_price
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private BigDecimal productTotalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.product_pieces
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private Integer productPieces;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.product_netweight
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private BigDecimal productNetweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.pic_url
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.create_operator
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private String createOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.create_time
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.upt_operator
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private String uptOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.upt_time
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private Date uptTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.is_del
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private Boolean isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.factory_no
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private String factoryNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.currency_rate
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private BigDecimal currencyRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_trade_item.risk_price
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    private BigDecimal riskPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.id
     *
     * @return the value of od_order_trade_item.id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.id
     *
     * @param id the value for od_order_trade_item.id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.order_id
     *
     * @return the value of od_order_trade_item.order_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.order_id
     *
     * @param orderId the value for od_order_trade_item.order_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.trade_id
     *
     * @return the value of od_order_trade_item.trade_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public String getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.trade_id
     *
     * @param tradeId the value for od_order_trade_item.trade_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setTradeId(String tradeId) {
        this.tradeId = tradeId == null ? null : tradeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.category_id
     *
     * @return the value of od_order_trade_item.category_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.category_id
     *
     * @param categoryId the value for od_order_trade_item.category_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.category_name
     *
     * @return the value of od_order_trade_item.category_name
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.category_name
     *
     * @param categoryName the value for od_order_trade_item.category_name
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.country_id
     *
     * @return the value of od_order_trade_item.country_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public Integer getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.country_id
     *
     * @param countryId the value for od_order_trade_item.country_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.country_name
     *
     * @return the value of od_order_trade_item.country_name
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.country_name
     *
     * @param countryName the value for od_order_trade_item.country_name
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName == null ? null : countryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.product_id
     *
     * @return the value of od_order_trade_item.product_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.product_id
     *
     * @param productId the value for od_order_trade_item.product_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.stproduct_id
     *
     * @return the value of od_order_trade_item.stproduct_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public String getStproductId() {
        return stproductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.stproduct_id
     *
     * @param stproductId the value for od_order_trade_item.stproduct_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setStproductId(String stproductId) {
        this.stproductId = stproductId == null ? null : stproductId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.product_name
     *
     * @return the value of od_order_trade_item.product_name
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.product_name
     *
     * @param productName the value for od_order_trade_item.product_name
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.en_name
     *
     * @return the value of od_order_trade_item.en_name
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.en_name
     *
     * @param enName the value for od_order_trade_item.en_name
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.hs_code
     *
     * @return the value of od_order_trade_item.hs_code
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public String getHsCode() {
        return hsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.hs_code
     *
     * @param hsCode the value for od_order_trade_item.hs_code
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setHsCode(String hsCode) {
        this.hsCode = hsCode == null ? null : hsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.product_spec
     *
     * @return the value of od_order_trade_item.product_spec
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public String getProductSpec() {
        return productSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.product_spec
     *
     * @param productSpec the value for od_order_trade_item.product_spec
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setProductSpec(String productSpec) {
        this.productSpec = productSpec == null ? null : productSpec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.product_amount
     *
     * @return the value of od_order_trade_item.product_amount
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public BigDecimal getProductAmount() {
        return productAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.product_amount
     *
     * @param productAmount the value for od_order_trade_item.product_amount
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setProductAmount(BigDecimal productAmount) {
        this.productAmount = productAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.product_unit_id
     *
     * @return the value of od_order_trade_item.product_unit_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public Integer getProductUnitId() {
        return productUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.product_unit_id
     *
     * @param productUnitId the value for od_order_trade_item.product_unit_id
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setProductUnitId(Integer productUnitId) {
        this.productUnitId = productUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.product_sale_price
     *
     * @return the value of od_order_trade_item.product_sale_price
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public BigDecimal getProductSalePrice() {
        return productSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.product_sale_price
     *
     * @param productSalePrice the value for od_order_trade_item.product_sale_price
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setProductSalePrice(BigDecimal productSalePrice) {
        this.productSalePrice = productSalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.product_total_price
     *
     * @return the value of od_order_trade_item.product_total_price
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public BigDecimal getProductTotalPrice() {
        return productTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.product_total_price
     *
     * @param productTotalPrice the value for od_order_trade_item.product_total_price
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setProductTotalPrice(BigDecimal productTotalPrice) {
        this.productTotalPrice = productTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.product_pieces
     *
     * @return the value of od_order_trade_item.product_pieces
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public Integer getProductPieces() {
        return productPieces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.product_pieces
     *
     * @param productPieces the value for od_order_trade_item.product_pieces
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setProductPieces(Integer productPieces) {
        this.productPieces = productPieces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.product_netweight
     *
     * @return the value of od_order_trade_item.product_netweight
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public BigDecimal getProductNetweight() {
        return productNetweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.product_netweight
     *
     * @param productNetweight the value for od_order_trade_item.product_netweight
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setProductNetweight(BigDecimal productNetweight) {
        this.productNetweight = productNetweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.pic_url
     *
     * @return the value of od_order_trade_item.pic_url
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.pic_url
     *
     * @param picUrl the value for od_order_trade_item.pic_url
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.create_operator
     *
     * @return the value of od_order_trade_item.create_operator
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public String getCreateOperator() {
        return createOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.create_operator
     *
     * @param createOperator the value for od_order_trade_item.create_operator
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setCreateOperator(String createOperator) {
        this.createOperator = createOperator == null ? null : createOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.create_time
     *
     * @return the value of od_order_trade_item.create_time
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.create_time
     *
     * @param createTime the value for od_order_trade_item.create_time
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.upt_operator
     *
     * @return the value of od_order_trade_item.upt_operator
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public String getUptOperator() {
        return uptOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.upt_operator
     *
     * @param uptOperator the value for od_order_trade_item.upt_operator
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setUptOperator(String uptOperator) {
        this.uptOperator = uptOperator == null ? null : uptOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.upt_time
     *
     * @return the value of od_order_trade_item.upt_time
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public Date getUptTime() {
        return uptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.upt_time
     *
     * @param uptTime the value for od_order_trade_item.upt_time
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setUptTime(Date uptTime) {
        this.uptTime = uptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.is_del
     *
     * @return the value of od_order_trade_item.is_del
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.is_del
     *
     * @param isDel the value for od_order_trade_item.is_del
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.factory_no
     *
     * @return the value of od_order_trade_item.factory_no
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public String getFactoryNo() {
        return factoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.factory_no
     *
     * @param factoryNo the value for od_order_trade_item.factory_no
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setFactoryNo(String factoryNo) {
        this.factoryNo = factoryNo == null ? null : factoryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.currency_rate
     *
     * @return the value of od_order_trade_item.currency_rate
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public BigDecimal getCurrencyRate() {
        return currencyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.currency_rate
     *
     * @param currencyRate the value for od_order_trade_item.currency_rate
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setCurrencyRate(BigDecimal currencyRate) {
        this.currencyRate = currencyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_trade_item.risk_price
     *
     * @return the value of od_order_trade_item.risk_price
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public BigDecimal getRiskPrice() {
        return riskPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_trade_item.risk_price
     *
     * @param riskPrice the value for od_order_trade_item.risk_price
     *
     * @mbg.generated Wed Jan 03 13:01:14 CST 2018
     */
    public void setRiskPrice(BigDecimal riskPrice) {
        this.riskPrice = riskPrice;
    }
}