package com.shiwulian.wechat.bean.od;

import java.util.Date;

public class OrderExecutionplan {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column od_order_execution_plan.id
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column od_order_execution_plan.order_id
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column od_order_execution_plan.server_id
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	private Integer serverId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column od_order_execution_plan.work_id
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	private Integer workId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column od_order_execution_plan.status
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column od_order_execution_plan.act_partnerid
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	private String actPartnerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column od_order_execution_plan.act_operator
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	private String actOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column od_order_execution_plan.sort
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column od_order_execution_plan.complete_time
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	private Date completeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column od_order_execution_plan.action_content
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	private String actionContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column od_order_execution_plan.create_operator
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	private String createOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column od_order_execution_plan.create_time
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column od_order_execution_plan.upt_operator
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	private String uptOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column od_order_execution_plan.upt_time
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	private Date uptTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column od_order_execution_plan.is_del
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	private Boolean isDel;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column od_order_execution_plan.id
	 * @return  the value of od_order_execution_plan.id
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column od_order_execution_plan.id
	 * @param id  the value for od_order_execution_plan.id
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column od_order_execution_plan.order_id
	 * @return  the value of od_order_execution_plan.order_id
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column od_order_execution_plan.order_id
	 * @param orderId  the value for od_order_execution_plan.order_id
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId == null ? null : orderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column od_order_execution_plan.server_id
	 * @return  the value of od_order_execution_plan.server_id
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public Integer getServerId() {
		return serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column od_order_execution_plan.server_id
	 * @param serverId  the value for od_order_execution_plan.server_id
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public void setServerId(Integer serverId) {
		this.serverId = serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column od_order_execution_plan.work_id
	 * @return  the value of od_order_execution_plan.work_id
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public Integer getWorkId() {
		return workId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column od_order_execution_plan.work_id
	 * @param workId  the value for od_order_execution_plan.work_id
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public void setWorkId(Integer workId) {
		this.workId = workId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column od_order_execution_plan.status
	 * @return  the value of od_order_execution_plan.status
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column od_order_execution_plan.status
	 * @param status  the value for od_order_execution_plan.status
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column od_order_execution_plan.act_partnerid
	 * @return  the value of od_order_execution_plan.act_partnerid
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public String getActPartnerid() {
		return actPartnerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column od_order_execution_plan.act_partnerid
	 * @param actPartnerid  the value for od_order_execution_plan.act_partnerid
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public void setActPartnerid(String actPartnerid) {
		this.actPartnerid = actPartnerid == null ? null : actPartnerid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column od_order_execution_plan.act_operator
	 * @return  the value of od_order_execution_plan.act_operator
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public String getActOperator() {
		return actOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column od_order_execution_plan.act_operator
	 * @param actOperator  the value for od_order_execution_plan.act_operator
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public void setActOperator(String actOperator) {
		this.actOperator = actOperator == null ? null : actOperator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column od_order_execution_plan.sort
	 * @return  the value of od_order_execution_plan.sort
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column od_order_execution_plan.sort
	 * @param sort  the value for od_order_execution_plan.sort
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column od_order_execution_plan.complete_time
	 * @return  the value of od_order_execution_plan.complete_time
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public Date getCompleteTime() {
		return completeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column od_order_execution_plan.complete_time
	 * @param completeTime  the value for od_order_execution_plan.complete_time
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public void setCompleteTime(Date completeTime) {
		this.completeTime = completeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column od_order_execution_plan.action_content
	 * @return  the value of od_order_execution_plan.action_content
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public String getActionContent() {
		return actionContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column od_order_execution_plan.action_content
	 * @param actionContent  the value for od_order_execution_plan.action_content
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public void setActionContent(String actionContent) {
		this.actionContent = actionContent == null ? null : actionContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column od_order_execution_plan.create_operator
	 * @return  the value of od_order_execution_plan.create_operator
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public String getCreateOperator() {
		return createOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column od_order_execution_plan.create_operator
	 * @param createOperator  the value for od_order_execution_plan.create_operator
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public void setCreateOperator(String createOperator) {
		this.createOperator = createOperator == null ? null : createOperator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column od_order_execution_plan.create_time
	 * @return  the value of od_order_execution_plan.create_time
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column od_order_execution_plan.create_time
	 * @param createTime  the value for od_order_execution_plan.create_time
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column od_order_execution_plan.upt_operator
	 * @return  the value of od_order_execution_plan.upt_operator
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public String getUptOperator() {
		return uptOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column od_order_execution_plan.upt_operator
	 * @param uptOperator  the value for od_order_execution_plan.upt_operator
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public void setUptOperator(String uptOperator) {
		this.uptOperator = uptOperator == null ? null : uptOperator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column od_order_execution_plan.upt_time
	 * @return  the value of od_order_execution_plan.upt_time
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public Date getUptTime() {
		return uptTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column od_order_execution_plan.upt_time
	 * @param uptTime  the value for od_order_execution_plan.upt_time
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public void setUptTime(Date uptTime) {
		this.uptTime = uptTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column od_order_execution_plan.is_del
	 * @return  the value of od_order_execution_plan.is_del
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public Boolean getIsDel() {
		return isDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column od_order_execution_plan.is_del
	 * @param isDel  the value for od_order_execution_plan.is_del
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	public void setIsDel(Boolean isDel) {
		this.isDel = isDel;
	}
}