package com.shiwulian.wechat.bean.od;

import java.math.BigDecimal;
import java.util.Date;

public class OrderExecutiveInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.order_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.recdoc_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Date recdocDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.shipping_company_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String shippingCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.shipping_company_name
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String shippingCompanyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.shipname
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String shipname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.voyage_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String voyageNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.eta
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Date eta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.bill_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String billNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.container_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String containerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.container_num
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Integer containerNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.container_unitid
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Integer containerUnitid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.totalpieces
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Integer totalpieces;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.totalgrossweight
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private BigDecimal totalgrossweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.totalnetweight
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private BigDecimal totalnetweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.ata
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Date ata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.port_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Integer portId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.dock_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Integer dockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.dock_name
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String dockName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.customs_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String customsNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.declaration_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Date declarationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.customs_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Date customsDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.inspection_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String inspectionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.customs_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Integer customsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.ciq_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Integer ciqId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.delivery_name
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String deliveryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.delivery_car_number
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String deliveryCarNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.delivery_phone
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String deliveryPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.delivery_start_time
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Date deliveryStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.delivery_end_time
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Date deliveryEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.storage_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Date storageDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.autoimportlicense_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String autoimportlicenseNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.autoimportlicense_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String autoimportlicenseMemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.entryinspectionlicense_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String entryinspectionlicenseNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.entryinspectionlicense_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String entryinspectionlicenseMemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.customs_broker_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String customsBrokerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.shipping_info_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String shippingInfoMemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.preinspection_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Date preinspectionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.preinspection_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String preinspectionMemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.changebill_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Date changebillDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.changebill_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String changebillMemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.predeclaration_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String predeclarationNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.predeclaration_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String predeclarationMemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.is_tariffout
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Boolean isTariffout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.tariff_fee
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private BigDecimal tariffFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.vat_fee
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private BigDecimal vatFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.excise_fee
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private BigDecimal exciseFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.delay_fee
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private BigDecimal delayFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.sampling_state
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Integer samplingState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.sampling_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String samplingMemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.create_operator
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String createOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.create_time
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.upt_operator
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private String uptOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.upt_time
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Date uptTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_executive_info.is_del
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.order_id
     *
     * @return the value of od_order_executive_info.order_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.order_id
     *
     * @param orderId the value for od_order_executive_info.order_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.recdoc_date
     *
     * @return the value of od_order_executive_info.recdoc_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Date getRecdocDate() {
        return recdocDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.recdoc_date
     *
     * @param recdocDate the value for od_order_executive_info.recdoc_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setRecdocDate(Date recdocDate) {
        this.recdocDate = recdocDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.shipping_company_id
     *
     * @return the value of od_order_executive_info.shipping_company_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getShippingCompanyId() {
        return shippingCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.shipping_company_id
     *
     * @param shippingCompanyId the value for od_order_executive_info.shipping_company_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setShippingCompanyId(String shippingCompanyId) {
        this.shippingCompanyId = shippingCompanyId == null ? null : shippingCompanyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.shipping_company_name
     *
     * @return the value of od_order_executive_info.shipping_company_name
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getShippingCompanyName() {
        return shippingCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.shipping_company_name
     *
     * @param shippingCompanyName the value for od_order_executive_info.shipping_company_name
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setShippingCompanyName(String shippingCompanyName) {
        this.shippingCompanyName = shippingCompanyName == null ? null : shippingCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.shipname
     *
     * @return the value of od_order_executive_info.shipname
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getShipname() {
        return shipname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.shipname
     *
     * @param shipname the value for od_order_executive_info.shipname
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setShipname(String shipname) {
        this.shipname = shipname == null ? null : shipname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.voyage_no
     *
     * @return the value of od_order_executive_info.voyage_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getVoyageNo() {
        return voyageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.voyage_no
     *
     * @param voyageNo the value for od_order_executive_info.voyage_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setVoyageNo(String voyageNo) {
        this.voyageNo = voyageNo == null ? null : voyageNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.eta
     *
     * @return the value of od_order_executive_info.eta
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Date getEta() {
        return eta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.eta
     *
     * @param eta the value for od_order_executive_info.eta
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setEta(Date eta) {
        this.eta = eta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.bill_no
     *
     * @return the value of od_order_executive_info.bill_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.bill_no
     *
     * @param billNo the value for od_order_executive_info.bill_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo == null ? null : billNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.container_no
     *
     * @return the value of od_order_executive_info.container_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getContainerNo() {
        return containerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.container_no
     *
     * @param containerNo the value for od_order_executive_info.container_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setContainerNo(String containerNo) {
        this.containerNo = containerNo == null ? null : containerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.container_num
     *
     * @return the value of od_order_executive_info.container_num
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Integer getContainerNum() {
        return containerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.container_num
     *
     * @param containerNum the value for od_order_executive_info.container_num
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setContainerNum(Integer containerNum) {
        this.containerNum = containerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.container_unitid
     *
     * @return the value of od_order_executive_info.container_unitid
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Integer getContainerUnitid() {
        return containerUnitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.container_unitid
     *
     * @param containerUnitid the value for od_order_executive_info.container_unitid
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setContainerUnitid(Integer containerUnitid) {
        this.containerUnitid = containerUnitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.totalpieces
     *
     * @return the value of od_order_executive_info.totalpieces
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Integer getTotalpieces() {
        return totalpieces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.totalpieces
     *
     * @param totalpieces the value for od_order_executive_info.totalpieces
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setTotalpieces(Integer totalpieces) {
        this.totalpieces = totalpieces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.totalgrossweight
     *
     * @return the value of od_order_executive_info.totalgrossweight
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public BigDecimal getTotalgrossweight() {
        return totalgrossweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.totalgrossweight
     *
     * @param totalgrossweight the value for od_order_executive_info.totalgrossweight
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setTotalgrossweight(BigDecimal totalgrossweight) {
        this.totalgrossweight = totalgrossweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.totalnetweight
     *
     * @return the value of od_order_executive_info.totalnetweight
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public BigDecimal getTotalnetweight() {
        return totalnetweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.totalnetweight
     *
     * @param totalnetweight the value for od_order_executive_info.totalnetweight
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setTotalnetweight(BigDecimal totalnetweight) {
        this.totalnetweight = totalnetweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.ata
     *
     * @return the value of od_order_executive_info.ata
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Date getAta() {
        return ata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.ata
     *
     * @param ata the value for od_order_executive_info.ata
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setAta(Date ata) {
        this.ata = ata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.port_id
     *
     * @return the value of od_order_executive_info.port_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Integer getPortId() {
        return portId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.port_id
     *
     * @param portId the value for od_order_executive_info.port_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setPortId(Integer portId) {
        this.portId = portId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.dock_id
     *
     * @return the value of od_order_executive_info.dock_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Integer getDockId() {
        return dockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.dock_id
     *
     * @param dockId the value for od_order_executive_info.dock_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setDockId(Integer dockId) {
        this.dockId = dockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.dock_name
     *
     * @return the value of od_order_executive_info.dock_name
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getDockName() {
        return dockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.dock_name
     *
     * @param dockName the value for od_order_executive_info.dock_name
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setDockName(String dockName) {
        this.dockName = dockName == null ? null : dockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.customs_no
     *
     * @return the value of od_order_executive_info.customs_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getCustomsNo() {
        return customsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.customs_no
     *
     * @param customsNo the value for od_order_executive_info.customs_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setCustomsNo(String customsNo) {
        this.customsNo = customsNo == null ? null : customsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.declaration_date
     *
     * @return the value of od_order_executive_info.declaration_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Date getDeclarationDate() {
        return declarationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.declaration_date
     *
     * @param declarationDate the value for od_order_executive_info.declaration_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setDeclarationDate(Date declarationDate) {
        this.declarationDate = declarationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.customs_date
     *
     * @return the value of od_order_executive_info.customs_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Date getCustomsDate() {
        return customsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.customs_date
     *
     * @param customsDate the value for od_order_executive_info.customs_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setCustomsDate(Date customsDate) {
        this.customsDate = customsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.inspection_no
     *
     * @return the value of od_order_executive_info.inspection_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getInspectionNo() {
        return inspectionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.inspection_no
     *
     * @param inspectionNo the value for od_order_executive_info.inspection_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setInspectionNo(String inspectionNo) {
        this.inspectionNo = inspectionNo == null ? null : inspectionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.customs_id
     *
     * @return the value of od_order_executive_info.customs_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Integer getCustomsId() {
        return customsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.customs_id
     *
     * @param customsId the value for od_order_executive_info.customs_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setCustomsId(Integer customsId) {
        this.customsId = customsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.ciq_id
     *
     * @return the value of od_order_executive_info.ciq_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Integer getCiqId() {
        return ciqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.ciq_id
     *
     * @param ciqId the value for od_order_executive_info.ciq_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setCiqId(Integer ciqId) {
        this.ciqId = ciqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.delivery_name
     *
     * @return the value of od_order_executive_info.delivery_name
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getDeliveryName() {
        return deliveryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.delivery_name
     *
     * @param deliveryName the value for od_order_executive_info.delivery_name
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setDeliveryName(String deliveryName) {
        this.deliveryName = deliveryName == null ? null : deliveryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.delivery_car_number
     *
     * @return the value of od_order_executive_info.delivery_car_number
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getDeliveryCarNumber() {
        return deliveryCarNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.delivery_car_number
     *
     * @param deliveryCarNumber the value for od_order_executive_info.delivery_car_number
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setDeliveryCarNumber(String deliveryCarNumber) {
        this.deliveryCarNumber = deliveryCarNumber == null ? null : deliveryCarNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.delivery_phone
     *
     * @return the value of od_order_executive_info.delivery_phone
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getDeliveryPhone() {
        return deliveryPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.delivery_phone
     *
     * @param deliveryPhone the value for od_order_executive_info.delivery_phone
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setDeliveryPhone(String deliveryPhone) {
        this.deliveryPhone = deliveryPhone == null ? null : deliveryPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.delivery_start_time
     *
     * @return the value of od_order_executive_info.delivery_start_time
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Date getDeliveryStartTime() {
        return deliveryStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.delivery_start_time
     *
     * @param deliveryStartTime the value for od_order_executive_info.delivery_start_time
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setDeliveryStartTime(Date deliveryStartTime) {
        this.deliveryStartTime = deliveryStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.delivery_end_time
     *
     * @return the value of od_order_executive_info.delivery_end_time
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Date getDeliveryEndTime() {
        return deliveryEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.delivery_end_time
     *
     * @param deliveryEndTime the value for od_order_executive_info.delivery_end_time
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setDeliveryEndTime(Date deliveryEndTime) {
        this.deliveryEndTime = deliveryEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.storage_date
     *
     * @return the value of od_order_executive_info.storage_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Date getStorageDate() {
        return storageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.storage_date
     *
     * @param storageDate the value for od_order_executive_info.storage_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setStorageDate(Date storageDate) {
        this.storageDate = storageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.autoimportlicense_no
     *
     * @return the value of od_order_executive_info.autoimportlicense_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getAutoimportlicenseNo() {
        return autoimportlicenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.autoimportlicense_no
     *
     * @param autoimportlicenseNo the value for od_order_executive_info.autoimportlicense_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setAutoimportlicenseNo(String autoimportlicenseNo) {
        this.autoimportlicenseNo = autoimportlicenseNo == null ? null : autoimportlicenseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.autoimportlicense_memo
     *
     * @return the value of od_order_executive_info.autoimportlicense_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getAutoimportlicenseMemo() {
        return autoimportlicenseMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.autoimportlicense_memo
     *
     * @param autoimportlicenseMemo the value for od_order_executive_info.autoimportlicense_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setAutoimportlicenseMemo(String autoimportlicenseMemo) {
        this.autoimportlicenseMemo = autoimportlicenseMemo == null ? null : autoimportlicenseMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.entryinspectionlicense_no
     *
     * @return the value of od_order_executive_info.entryinspectionlicense_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getEntryinspectionlicenseNo() {
        return entryinspectionlicenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.entryinspectionlicense_no
     *
     * @param entryinspectionlicenseNo the value for od_order_executive_info.entryinspectionlicense_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setEntryinspectionlicenseNo(String entryinspectionlicenseNo) {
        this.entryinspectionlicenseNo = entryinspectionlicenseNo == null ? null : entryinspectionlicenseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.entryinspectionlicense_memo
     *
     * @return the value of od_order_executive_info.entryinspectionlicense_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getEntryinspectionlicenseMemo() {
        return entryinspectionlicenseMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.entryinspectionlicense_memo
     *
     * @param entryinspectionlicenseMemo the value for od_order_executive_info.entryinspectionlicense_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setEntryinspectionlicenseMemo(String entryinspectionlicenseMemo) {
        this.entryinspectionlicenseMemo = entryinspectionlicenseMemo == null ? null : entryinspectionlicenseMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.customs_broker_id
     *
     * @return the value of od_order_executive_info.customs_broker_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getCustomsBrokerId() {
        return customsBrokerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.customs_broker_id
     *
     * @param customsBrokerId the value for od_order_executive_info.customs_broker_id
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setCustomsBrokerId(String customsBrokerId) {
        this.customsBrokerId = customsBrokerId == null ? null : customsBrokerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.shipping_info_memo
     *
     * @return the value of od_order_executive_info.shipping_info_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getShippingInfoMemo() {
        return shippingInfoMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.shipping_info_memo
     *
     * @param shippingInfoMemo the value for od_order_executive_info.shipping_info_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setShippingInfoMemo(String shippingInfoMemo) {
        this.shippingInfoMemo = shippingInfoMemo == null ? null : shippingInfoMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.preinspection_date
     *
     * @return the value of od_order_executive_info.preinspection_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Date getPreinspectionDate() {
        return preinspectionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.preinspection_date
     *
     * @param preinspectionDate the value for od_order_executive_info.preinspection_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setPreinspectionDate(Date preinspectionDate) {
        this.preinspectionDate = preinspectionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.preinspection_memo
     *
     * @return the value of od_order_executive_info.preinspection_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getPreinspectionMemo() {
        return preinspectionMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.preinspection_memo
     *
     * @param preinspectionMemo the value for od_order_executive_info.preinspection_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setPreinspectionMemo(String preinspectionMemo) {
        this.preinspectionMemo = preinspectionMemo == null ? null : preinspectionMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.changebill_date
     *
     * @return the value of od_order_executive_info.changebill_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Date getChangebillDate() {
        return changebillDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.changebill_date
     *
     * @param changebillDate the value for od_order_executive_info.changebill_date
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setChangebillDate(Date changebillDate) {
        this.changebillDate = changebillDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.changebill_memo
     *
     * @return the value of od_order_executive_info.changebill_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getChangebillMemo() {
        return changebillMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.changebill_memo
     *
     * @param changebillMemo the value for od_order_executive_info.changebill_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setChangebillMemo(String changebillMemo) {
        this.changebillMemo = changebillMemo == null ? null : changebillMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.predeclaration_no
     *
     * @return the value of od_order_executive_info.predeclaration_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getPredeclarationNo() {
        return predeclarationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.predeclaration_no
     *
     * @param predeclarationNo the value for od_order_executive_info.predeclaration_no
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setPredeclarationNo(String predeclarationNo) {
        this.predeclarationNo = predeclarationNo == null ? null : predeclarationNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.predeclaration_memo
     *
     * @return the value of od_order_executive_info.predeclaration_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getPredeclarationMemo() {
        return predeclarationMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.predeclaration_memo
     *
     * @param predeclarationMemo the value for od_order_executive_info.predeclaration_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setPredeclarationMemo(String predeclarationMemo) {
        this.predeclarationMemo = predeclarationMemo == null ? null : predeclarationMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.is_tariffout
     *
     * @return the value of od_order_executive_info.is_tariffout
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Boolean getIsTariffout() {
        return isTariffout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.is_tariffout
     *
     * @param isTariffout the value for od_order_executive_info.is_tariffout
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setIsTariffout(Boolean isTariffout) {
        this.isTariffout = isTariffout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.tariff_fee
     *
     * @return the value of od_order_executive_info.tariff_fee
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public BigDecimal getTariffFee() {
        return tariffFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.tariff_fee
     *
     * @param tariffFee the value for od_order_executive_info.tariff_fee
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setTariffFee(BigDecimal tariffFee) {
        this.tariffFee = tariffFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.vat_fee
     *
     * @return the value of od_order_executive_info.vat_fee
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public BigDecimal getVatFee() {
        return vatFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.vat_fee
     *
     * @param vatFee the value for od_order_executive_info.vat_fee
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setVatFee(BigDecimal vatFee) {
        this.vatFee = vatFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.excise_fee
     *
     * @return the value of od_order_executive_info.excise_fee
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public BigDecimal getExciseFee() {
        return exciseFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.excise_fee
     *
     * @param exciseFee the value for od_order_executive_info.excise_fee
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setExciseFee(BigDecimal exciseFee) {
        this.exciseFee = exciseFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.delay_fee
     *
     * @return the value of od_order_executive_info.delay_fee
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public BigDecimal getDelayFee() {
        return delayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.delay_fee
     *
     * @param delayFee the value for od_order_executive_info.delay_fee
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setDelayFee(BigDecimal delayFee) {
        this.delayFee = delayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.sampling_state
     *
     * @return the value of od_order_executive_info.sampling_state
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Integer getSamplingState() {
        return samplingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.sampling_state
     *
     * @param samplingState the value for od_order_executive_info.sampling_state
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setSamplingState(Integer samplingState) {
        this.samplingState = samplingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.sampling_memo
     *
     * @return the value of od_order_executive_info.sampling_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getSamplingMemo() {
        return samplingMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.sampling_memo
     *
     * @param samplingMemo the value for od_order_executive_info.sampling_memo
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setSamplingMemo(String samplingMemo) {
        this.samplingMemo = samplingMemo == null ? null : samplingMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.create_operator
     *
     * @return the value of od_order_executive_info.create_operator
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getCreateOperator() {
        return createOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.create_operator
     *
     * @param createOperator the value for od_order_executive_info.create_operator
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setCreateOperator(String createOperator) {
        this.createOperator = createOperator == null ? null : createOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.create_time
     *
     * @return the value of od_order_executive_info.create_time
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.create_time
     *
     * @param createTime the value for od_order_executive_info.create_time
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.upt_operator
     *
     * @return the value of od_order_executive_info.upt_operator
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public String getUptOperator() {
        return uptOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.upt_operator
     *
     * @param uptOperator the value for od_order_executive_info.upt_operator
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setUptOperator(String uptOperator) {
        this.uptOperator = uptOperator == null ? null : uptOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.upt_time
     *
     * @return the value of od_order_executive_info.upt_time
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Date getUptTime() {
        return uptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.upt_time
     *
     * @param uptTime the value for od_order_executive_info.upt_time
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setUptTime(Date uptTime) {
        this.uptTime = uptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_executive_info.is_del
     *
     * @return the value of od_order_executive_info.is_del
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_executive_info.is_del
     *
     * @param isDel the value for od_order_executive_info.is_del
     *
     * @mbg.generated Wed Jan 03 14:00:23 CST 2018
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}