package com.shiwulian.wechat.bean.od;

import java.util.Date;

public class OrderEvaluate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_evaluate.id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_evaluate.order_id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_evaluate.evaluate_server
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private Integer evaluateServer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_evaluate.evaluate_exec
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private Integer evaluateExec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_evaluate.evaluate_remark
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private String evaluateRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_evaluate.evaluate_time
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private Date evaluateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_evaluate.create_operator
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private String createOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_evaluate.create_time
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column od_order_evaluate.is_del
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_evaluate.id
     *
     * @return the value of od_order_evaluate.id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_evaluate.id
     *
     * @param id the value for od_order_evaluate.id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_evaluate.order_id
     *
     * @return the value of od_order_evaluate.order_id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_evaluate.order_id
     *
     * @param orderId the value for od_order_evaluate.order_id
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_evaluate.evaluate_server
     *
     * @return the value of od_order_evaluate.evaluate_server
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public Integer getEvaluateServer() {
        return evaluateServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_evaluate.evaluate_server
     *
     * @param evaluateServer the value for od_order_evaluate.evaluate_server
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setEvaluateServer(Integer evaluateServer) {
        this.evaluateServer = evaluateServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_evaluate.evaluate_exec
     *
     * @return the value of od_order_evaluate.evaluate_exec
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public Integer getEvaluateExec() {
        return evaluateExec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_evaluate.evaluate_exec
     *
     * @param evaluateExec the value for od_order_evaluate.evaluate_exec
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setEvaluateExec(Integer evaluateExec) {
        this.evaluateExec = evaluateExec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_evaluate.evaluate_remark
     *
     * @return the value of od_order_evaluate.evaluate_remark
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public String getEvaluateRemark() {
        return evaluateRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_evaluate.evaluate_remark
     *
     * @param evaluateRemark the value for od_order_evaluate.evaluate_remark
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setEvaluateRemark(String evaluateRemark) {
        this.evaluateRemark = evaluateRemark == null ? null : evaluateRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_evaluate.evaluate_time
     *
     * @return the value of od_order_evaluate.evaluate_time
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public Date getEvaluateTime() {
        return evaluateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_evaluate.evaluate_time
     *
     * @param evaluateTime the value for od_order_evaluate.evaluate_time
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setEvaluateTime(Date evaluateTime) {
        this.evaluateTime = evaluateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_evaluate.create_operator
     *
     * @return the value of od_order_evaluate.create_operator
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public String getCreateOperator() {
        return createOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_evaluate.create_operator
     *
     * @param createOperator the value for od_order_evaluate.create_operator
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setCreateOperator(String createOperator) {
        this.createOperator = createOperator == null ? null : createOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_evaluate.create_time
     *
     * @return the value of od_order_evaluate.create_time
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_evaluate.create_time
     *
     * @param createTime the value for od_order_evaluate.create_time
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column od_order_evaluate.is_del
     *
     * @return the value of od_order_evaluate.is_del
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column od_order_evaluate.is_del
     *
     * @param isDel the value for od_order_evaluate.is_del
     *
     * @mbg.generated Tue Oct 10 10:46:46 CST 2017
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}