package com.xhhxd.retail.bean.bs;

import java.util.Date;

public class BsUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.id
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.username
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.nickname
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.portrait
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private String portrait;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.gender
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private Boolean gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.mobile
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.password
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.email
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.birthday
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.verify_mobile
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private Boolean verifyMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.verify_email
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private Boolean verifyEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.user_type
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private Integer userType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.team_id
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private String teamId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.create_from
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private Integer createFrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.create_user
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.create_time
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.last_login_time
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private Date lastLoginTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.status
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.is_del
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	private Boolean isDel;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.id
	 * @return  the value of bs_user.id
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.id
	 * @param id  the value for bs_user.id
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.username
	 * @return  the value of bs_user.username
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.username
	 * @param username  the value for bs_user.username
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.nickname
	 * @return  the value of bs_user.nickname
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.nickname
	 * @param nickname  the value for bs_user.nickname
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname == null ? null : nickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.portrait
	 * @return  the value of bs_user.portrait
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public String getPortrait() {
		return portrait;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.portrait
	 * @param portrait  the value for bs_user.portrait
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setPortrait(String portrait) {
		this.portrait = portrait == null ? null : portrait.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.gender
	 * @return  the value of bs_user.gender
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public Boolean getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.gender
	 * @param gender  the value for bs_user.gender
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setGender(Boolean gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.mobile
	 * @return  the value of bs_user.mobile
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.mobile
	 * @param mobile  the value for bs_user.mobile
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.password
	 * @return  the value of bs_user.password
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.password
	 * @param password  the value for bs_user.password
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.email
	 * @return  the value of bs_user.email
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.email
	 * @param email  the value for bs_user.email
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.birthday
	 * @return  the value of bs_user.birthday
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.birthday
	 * @param birthday  the value for bs_user.birthday
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.verify_mobile
	 * @return  the value of bs_user.verify_mobile
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public Boolean getVerifyMobile() {
		return verifyMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.verify_mobile
	 * @param verifyMobile  the value for bs_user.verify_mobile
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setVerifyMobile(Boolean verifyMobile) {
		this.verifyMobile = verifyMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.verify_email
	 * @return  the value of bs_user.verify_email
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public Boolean getVerifyEmail() {
		return verifyEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.verify_email
	 * @param verifyEmail  the value for bs_user.verify_email
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setVerifyEmail(Boolean verifyEmail) {
		this.verifyEmail = verifyEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.user_type
	 * @return  the value of bs_user.user_type
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public Integer getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.user_type
	 * @param userType  the value for bs_user.user_type
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.team_id
	 * @return  the value of bs_user.team_id
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public String getTeamId() {
		return teamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.team_id
	 * @param teamId  the value for bs_user.team_id
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setTeamId(String teamId) {
		this.teamId = teamId == null ? null : teamId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.create_from
	 * @return  the value of bs_user.create_from
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public Integer getCreateFrom() {
		return createFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.create_from
	 * @param createFrom  the value for bs_user.create_from
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setCreateFrom(Integer createFrom) {
		this.createFrom = createFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.create_user
	 * @return  the value of bs_user.create_user
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.create_user
	 * @param createUser  the value for bs_user.create_user
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.create_time
	 * @return  the value of bs_user.create_time
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.create_time
	 * @param createTime  the value for bs_user.create_time
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.last_login_time
	 * @return  the value of bs_user.last_login_time
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.last_login_time
	 * @param lastLoginTime  the value for bs_user.last_login_time
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.status
	 * @return  the value of bs_user.status
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.status
	 * @param status  the value for bs_user.status
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.is_del
	 * @return  the value of bs_user.is_del
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public Boolean getIsDel() {
		return isDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.is_del
	 * @param isDel  the value for bs_user.is_del
	 * @mbg.generated  Mon Jun 04 14:48:35 CST 2018
	 */
	public void setIsDel(Boolean isDel) {
		this.isDel = isDel;
	}
}