package com.xhhxd.retail.mapper.sys;

import com.xhhxd.retail.bean.sys.SysProvince;

public interface SysProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_province
     *
     * @mbg.generated Mon Jun 04 10:16:56 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_province
     *
     * @mbg.generated Mon Jun 04 10:16:56 CST 2018
     */
    int insert(SysProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_province
     *
     * @mbg.generated Mon Jun 04 10:16:56 CST 2018
     */
    int insertSelective(SysProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_province
     *
     * @mbg.generated Mon Jun 04 10:16:56 CST 2018
     */
    SysProvince selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_province
     *
     * @mbg.generated Mon Jun 04 10:16:56 CST 2018
     */
    int updateByPrimaryKeySelective(SysProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_province
     *
     * @mbg.generated Mon Jun 04 10:16:56 CST 2018
     */
    int updateByPrimaryKey(SysProvince record);
}