package com.shiwulian.wechat.mapper.od;

import com.shiwulian.wechat.bean.od.OrderStorage;

public interface OrderStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_order_storage
     *
     * @mbg.generated Wed Jan 03 13:11:33 CST 2018
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_order_storage
     *
     * @mbg.generated Wed Jan 03 13:11:33 CST 2018
     */
    int insert(OrderStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_order_storage
     *
     * @mbg.generated Wed Jan 03 13:11:33 CST 2018
     */
    int insertSelective(OrderStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_order_storage
     *
     * @mbg.generated Wed Jan 03 13:11:33 CST 2018
     */
    OrderStorage selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_order_storage
     *
     * @mbg.generated Wed Jan 03 13:11:33 CST 2018
     */
    int updateByPrimaryKeySelective(OrderStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_order_storage
     *
     * @mbg.generated Wed Jan 03 13:11:33 CST 2018
     */
    int updateByPrimaryKey(OrderStorage record);
}