package com.shiwulian.wechat.mapper.od;

import java.util.List;
import java.util.Map;

import com.shiwulian.wechat.bean.od.OrderDocument;

public interface OrderDocumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_order_document
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_order_document
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    int insert(OrderDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_order_document
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    int insertSelective(OrderDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_order_document
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    OrderDocument selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_order_document
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    int updateByPrimaryKeySelective(OrderDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table od_order_document
     *
     * @mbg.generated Wed Jan 03 13:22:08 CST 2018
     */
    int updateByPrimaryKey(OrderDocument record);
	/**
	 * 订单单据逻辑删除【没有上传人和上传时间/根据订单号】 
	 * @param map (orderId/uptOperator/uptTime)
	 */
	int isDelDocumentByUnUpload(Map<String,Object> map);
    
    List<OrderDocument> selectList(String orderId);
}