package com.shiwulian.wechat.mapper.od;

import java.util.List;
import java.util.Map;

import com.shiwulian.wechat.bean.od.OrderExecutionplan;
import com.shiwulian.wechat.bean.response.OrderExecutionPlanResponse;
import com.shiwulian.wechat.bean.response.OrderWorkResponse;


public interface OrderExecutionplanMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table od_order_execution_plan
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table od_order_execution_plan
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	int insert(OrderExecutionplan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table od_order_execution_plan
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	int insertSelective(OrderExecutionplan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table od_order_execution_plan
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	OrderExecutionplan selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table od_order_execution_plan
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	int updateByPrimaryKeySelective(OrderExecutionplan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table od_order_execution_plan
	 * @mbg.generated  Thu Nov 02 17:20:56 CST 2017
	 */
	int updateByPrimaryKey(OrderExecutionplan record);
	/**
	 * 物理删除
	 */
	int deleteByOrderId(String orderId);
	
	List<OrderWorkResponse> selectParam(Map<String,Object> map);
	OrderWorkResponse selectByCustomerId(String customerId);
	
    
    List<OrderExecutionPlanResponse> selectServerGroupByOrderIds(List<String> list);
}