package com.shiwulian.wechat.bean.sys;

public class Bank {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_bank.id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_bank.bank_name
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_bank.sort
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_bank.valid
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Boolean valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_bank.id
     *
     * @return the value of sys_bank.id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_bank.id
     *
     * @param id the value for sys_bank.id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_bank.bank_name
     *
     * @return the value of sys_bank.bank_name
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_bank.bank_name
     *
     * @param bankName the value for sys_bank.bank_name
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_bank.sort
     *
     * @return the value of sys_bank.sort
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_bank.sort
     *
     * @param sort the value for sys_bank.sort
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_bank.valid
     *
     * @return the value of sys_bank.valid
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_bank.valid
     *
     * @param valid the value for sys_bank.valid
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}