package com.shiwulian.wechat.bean.sys;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.province_code
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Integer provinceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.city_code
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Integer cityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.city_name
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.sort
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.valid
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Boolean valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.id
     *
     * @return the value of sys_city.id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.id
     *
     * @param id the value for sys_city.id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.province_code
     *
     * @return the value of sys_city.province_code
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Integer getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.province_code
     *
     * @param provinceCode the value for sys_city.province_code
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setProvinceCode(Integer provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.city_code
     *
     * @return the value of sys_city.city_code
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Integer getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.city_code
     *
     * @param cityCode the value for sys_city.city_code
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setCityCode(Integer cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.city_name
     *
     * @return the value of sys_city.city_name
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.city_name
     *
     * @param cityName the value for sys_city.city_name
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.sort
     *
     * @return the value of sys_city.sort
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.sort
     *
     * @param sort the value for sys_city.sort
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.valid
     *
     * @return the value of sys_city.valid
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.valid
     *
     * @param valid the value for sys_city.valid
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}