package com.shiwulian.wechat.bean.sys;

public class Currency {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_currency.id
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_currency.currency_code
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	private String currencyCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_currency.currency_short_name
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	private String currencyShortName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_currency.currency_name
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	private String currencyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_currency.sort
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_currency.valid
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	private Boolean valid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_currency.id
	 * @return  the value of sys_currency.id
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_currency.id
	 * @param id  the value for sys_currency.id
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_currency.currency_code
	 * @return  the value of sys_currency.currency_code
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	public String getCurrencyCode() {
		return currencyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_currency.currency_code
	 * @param currencyCode  the value for sys_currency.currency_code
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode == null ? null : currencyCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_currency.currency_short_name
	 * @return  the value of sys_currency.currency_short_name
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	public String getCurrencyShortName() {
		return currencyShortName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_currency.currency_short_name
	 * @param currencyShortName  the value for sys_currency.currency_short_name
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	public void setCurrencyShortName(String currencyShortName) {
		this.currencyShortName = currencyShortName == null ? null : currencyShortName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_currency.currency_name
	 * @return  the value of sys_currency.currency_name
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	public String getCurrencyName() {
		return currencyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_currency.currency_name
	 * @param currencyName  the value for sys_currency.currency_name
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	public void setCurrencyName(String currencyName) {
		this.currencyName = currencyName == null ? null : currencyName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_currency.sort
	 * @return  the value of sys_currency.sort
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_currency.sort
	 * @param sort  the value for sys_currency.sort
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_currency.valid
	 * @return  the value of sys_currency.valid
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	public Boolean getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_currency.valid
	 * @param valid  the value for sys_currency.valid
	 * @mbg.generated  Mon Jan 08 15:19:48 CST 2018
	 */
	public void setValid(Boolean valid) {
		this.valid = valid;
	}
}