package com.shiwulian.wechat.bean.sys;

public class Customs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_customs.id
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_customs.customs_code
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    private String customsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_customs.customs_name
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    private String customsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_customs.customs_type
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    private Integer customsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_customs.city_id
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_customs.sort
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_customs.valid
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    private Boolean valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_customs.id
     *
     * @return the value of sys_customs.id
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_customs.id
     *
     * @param id the value for sys_customs.id
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_customs.customs_code
     *
     * @return the value of sys_customs.customs_code
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    public String getCustomsCode() {
        return customsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_customs.customs_code
     *
     * @param customsCode the value for sys_customs.customs_code
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    public void setCustomsCode(String customsCode) {
        this.customsCode = customsCode == null ? null : customsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_customs.customs_name
     *
     * @return the value of sys_customs.customs_name
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    public String getCustomsName() {
        return customsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_customs.customs_name
     *
     * @param customsName the value for sys_customs.customs_name
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    public void setCustomsName(String customsName) {
        this.customsName = customsName == null ? null : customsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_customs.customs_type
     *
     * @return the value of sys_customs.customs_type
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    public Integer getCustomsType() {
        return customsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_customs.customs_type
     *
     * @param customsType the value for sys_customs.customs_type
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    public void setCustomsType(Integer customsType) {
        this.customsType = customsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_customs.city_id
     *
     * @return the value of sys_customs.city_id
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_customs.city_id
     *
     * @param cityId the value for sys_customs.city_id
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_customs.sort
     *
     * @return the value of sys_customs.sort
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_customs.sort
     *
     * @param sort the value for sys_customs.sort
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_customs.valid
     *
     * @return the value of sys_customs.valid
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_customs.valid
     *
     * @param valid the value for sys_customs.valid
     *
     * @mbg.generated Thu Oct 19 10:57:45 CST 2017
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}