package com.shiwulian.wechat.bean.sys;

public class Dock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dock.id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dock.dock_name
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private String dockName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dock.port_id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Integer portId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dock.sort
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dock.valid
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Boolean valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dock.id
     *
     * @return the value of sys_dock.id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dock.id
     *
     * @param id the value for sys_dock.id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dock.dock_name
     *
     * @return the value of sys_dock.dock_name
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public String getDockName() {
        return dockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dock.dock_name
     *
     * @param dockName the value for sys_dock.dock_name
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setDockName(String dockName) {
        this.dockName = dockName == null ? null : dockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dock.port_id
     *
     * @return the value of sys_dock.port_id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Integer getPortId() {
        return portId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dock.port_id
     *
     * @param portId the value for sys_dock.port_id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setPortId(Integer portId) {
        this.portId = portId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dock.sort
     *
     * @return the value of sys_dock.sort
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dock.sort
     *
     * @param sort the value for sys_dock.sort
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dock.valid
     *
     * @return the value of sys_dock.valid
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dock.valid
     *
     * @param valid the value for sys_dock.valid
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}