package com.shiwulian.wechat.bean.sys;

public class PaymentTerm {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_payment_term.id
	 * @mbg.generated  Mon Jan 08 15:08:38 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_payment_term.term_name
	 * @mbg.generated  Mon Jan 08 15:08:38 CST 2018
	 */
	private String termName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_payment_term.category
	 * @mbg.generated  Mon Jan 08 15:08:38 CST 2018
	 */
	private Integer category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_payment_term.sort
	 * @mbg.generated  Mon Jan 08 15:08:38 CST 2018
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_payment_term.valid
	 * @mbg.generated  Mon Jan 08 15:08:38 CST 2018
	 */
	private Boolean valid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_payment_term.id
	 * @return  the value of sys_payment_term.id
	 * @mbg.generated  Mon Jan 08 15:08:38 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_payment_term.id
	 * @param id  the value for sys_payment_term.id
	 * @mbg.generated  Mon Jan 08 15:08:38 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_payment_term.term_name
	 * @return  the value of sys_payment_term.term_name
	 * @mbg.generated  Mon Jan 08 15:08:38 CST 2018
	 */
	public String getTermName() {
		return termName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_payment_term.term_name
	 * @param termName  the value for sys_payment_term.term_name
	 * @mbg.generated  Mon Jan 08 15:08:38 CST 2018
	 */
	public void setTermName(String termName) {
		this.termName = termName == null ? null : termName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_payment_term.category
	 * @return  the value of sys_payment_term.category
	 * @mbg.generated  Mon Jan 08 15:08:38 CST 2018
	 */
	public Integer getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_payment_term.category
	 * @param category  the value for sys_payment_term.category
	 * @mbg.generated  Mon Jan 08 15:08:38 CST 2018
	 */
	public void setCategory(Integer category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_payment_term.sort
	 * @return  the value of sys_payment_term.sort
	 * @mbg.generated  Mon Jan 08 15:08:38 CST 2018
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_payment_term.sort
	 * @param sort  the value for sys_payment_term.sort
	 * @mbg.generated  Mon Jan 08 15:08:38 CST 2018
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_payment_term.valid
	 * @return  the value of sys_payment_term.valid
	 * @mbg.generated  Mon Jan 08 15:08:38 CST 2018
	 */
	public Boolean getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_payment_term.valid
	 * @param valid  the value for sys_payment_term.valid
	 * @mbg.generated  Mon Jan 08 15:08:38 CST 2018
	 */
	public void setValid(Boolean valid) {
		this.valid = valid;
	}
}