package com.shiwulian.wechat.bean.sys;

public class Province {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_province.id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_province.provice_code
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Integer proviceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_province.provice_name
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private String proviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_province.sort
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_province.valid
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Boolean valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_province.id
     *
     * @return the value of sys_province.id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_province.id
     *
     * @param id the value for sys_province.id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_province.provice_code
     *
     * @return the value of sys_province.provice_code
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Integer getProviceCode() {
        return proviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_province.provice_code
     *
     * @param proviceCode the value for sys_province.provice_code
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setProviceCode(Integer proviceCode) {
        this.proviceCode = proviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_province.provice_name
     *
     * @return the value of sys_province.provice_name
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public String getProviceName() {
        return proviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_province.provice_name
     *
     * @param proviceName the value for sys_province.provice_name
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setProviceName(String proviceName) {
        this.proviceName = proviceName == null ? null : proviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_province.sort
     *
     * @return the value of sys_province.sort
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_province.sort
     *
     * @param sort the value for sys_province.sort
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_province.valid
     *
     * @return the value of sys_province.valid
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_province.valid
     *
     * @param valid the value for sys_province.valid
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}