package com.shiwulian.wechat.bean.sys;

public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.id
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.role_name
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.role_type
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	private Integer roleType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.sort
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.remark
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.valid
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	private Boolean valid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.id
	 * @return  the value of sys_role.id
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.id
	 * @param id  the value for sys_role.id
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.role_name
	 * @return  the value of sys_role.role_name
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.role_name
	 * @param roleName  the value for sys_role.role_name
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName == null ? null : roleName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.role_type
	 * @return  the value of sys_role.role_type
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	public Integer getRoleType() {
		return roleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.role_type
	 * @param roleType  the value for sys_role.role_type
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	public void setRoleType(Integer roleType) {
		this.roleType = roleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.sort
	 * @return  the value of sys_role.sort
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.sort
	 * @param sort  the value for sys_role.sort
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.remark
	 * @return  the value of sys_role.remark
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.remark
	 * @param remark  the value for sys_role.remark
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.valid
	 * @return  the value of sys_role.valid
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	public Boolean getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.valid
	 * @param valid  the value for sys_role.valid
	 * @mbg.generated  Thu Oct 19 10:57:45 CST 2017
	 */
	public void setValid(Boolean valid) {
		this.valid = valid;
	}
}