package com.shiwulian.wechat.bean.sys;

public class SettleType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_settletype.id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_settletype.settle_type
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private String settleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_settletype.sort
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_settletype.valid
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    private Boolean valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_settletype.id
     *
     * @return the value of sys_settletype.id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_settletype.id
     *
     * @param id the value for sys_settletype.id
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_settletype.settle_type
     *
     * @return the value of sys_settletype.settle_type
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public String getSettleType() {
        return settleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_settletype.settle_type
     *
     * @param settleType the value for sys_settletype.settle_type
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setSettleType(String settleType) {
        this.settleType = settleType == null ? null : settleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_settletype.sort
     *
     * @return the value of sys_settletype.sort
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_settletype.sort
     *
     * @param sort the value for sys_settletype.sort
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_settletype.valid
     *
     * @return the value of sys_settletype.valid
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_settletype.valid
     *
     * @param valid the value for sys_settletype.valid
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}