package com.shiwulian.wechat.bean.sys;

public class WorkType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_worktype.id
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_worktype.work_name
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	private String workName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_worktype.work_server_type_id
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	private Integer workServerTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_worktype.is_sea
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	private Boolean isSea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_worktype.is_sea_inner
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	private Boolean isSeaInner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_worktype.is_sea_inner_state
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	private Integer isSeaInnerState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_worktype.is_sea_out
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	private Boolean isSeaOut;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_worktype.is_sea_out_state
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	private Integer isSeaOutState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_worktype.is_air
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	private Boolean isAir;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_worktype.is_air_inner
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	private Boolean isAirInner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_worktype.is_air_inner_state
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	private Integer isAirInnerState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_worktype.is_air_out
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	private Boolean isAirOut;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_worktype.is_air_out_state
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	private Integer isAirOutState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_worktype.sort
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_worktype.valid
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	private Boolean valid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_worktype.id
	 * @return  the value of sys_worktype.id
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_worktype.id
	 * @param id  the value for sys_worktype.id
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_worktype.work_name
	 * @return  the value of sys_worktype.work_name
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public String getWorkName() {
		return workName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_worktype.work_name
	 * @param workName  the value for sys_worktype.work_name
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public void setWorkName(String workName) {
		this.workName = workName == null ? null : workName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_worktype.work_server_type_id
	 * @return  the value of sys_worktype.work_server_type_id
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public Integer getWorkServerTypeId() {
		return workServerTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_worktype.work_server_type_id
	 * @param workServerTypeId  the value for sys_worktype.work_server_type_id
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public void setWorkServerTypeId(Integer workServerTypeId) {
		this.workServerTypeId = workServerTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_worktype.is_sea
	 * @return  the value of sys_worktype.is_sea
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public Boolean getIsSea() {
		return isSea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_worktype.is_sea
	 * @param isSea  the value for sys_worktype.is_sea
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public void setIsSea(Boolean isSea) {
		this.isSea = isSea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_worktype.is_sea_inner
	 * @return  the value of sys_worktype.is_sea_inner
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public Boolean getIsSeaInner() {
		return isSeaInner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_worktype.is_sea_inner
	 * @param isSeaInner  the value for sys_worktype.is_sea_inner
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public void setIsSeaInner(Boolean isSeaInner) {
		this.isSeaInner = isSeaInner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_worktype.is_sea_inner_state
	 * @return  the value of sys_worktype.is_sea_inner_state
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public Integer getIsSeaInnerState() {
		return isSeaInnerState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_worktype.is_sea_inner_state
	 * @param isSeaInnerState  the value for sys_worktype.is_sea_inner_state
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public void setIsSeaInnerState(Integer isSeaInnerState) {
		this.isSeaInnerState = isSeaInnerState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_worktype.is_sea_out
	 * @return  the value of sys_worktype.is_sea_out
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public Boolean getIsSeaOut() {
		return isSeaOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_worktype.is_sea_out
	 * @param isSeaOut  the value for sys_worktype.is_sea_out
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public void setIsSeaOut(Boolean isSeaOut) {
		this.isSeaOut = isSeaOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_worktype.is_sea_out_state
	 * @return  the value of sys_worktype.is_sea_out_state
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public Integer getIsSeaOutState() {
		return isSeaOutState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_worktype.is_sea_out_state
	 * @param isSeaOutState  the value for sys_worktype.is_sea_out_state
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public void setIsSeaOutState(Integer isSeaOutState) {
		this.isSeaOutState = isSeaOutState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_worktype.is_air
	 * @return  the value of sys_worktype.is_air
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public Boolean getIsAir() {
		return isAir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_worktype.is_air
	 * @param isAir  the value for sys_worktype.is_air
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public void setIsAir(Boolean isAir) {
		this.isAir = isAir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_worktype.is_air_inner
	 * @return  the value of sys_worktype.is_air_inner
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public Boolean getIsAirInner() {
		return isAirInner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_worktype.is_air_inner
	 * @param isAirInner  the value for sys_worktype.is_air_inner
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public void setIsAirInner(Boolean isAirInner) {
		this.isAirInner = isAirInner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_worktype.is_air_inner_state
	 * @return  the value of sys_worktype.is_air_inner_state
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public Integer getIsAirInnerState() {
		return isAirInnerState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_worktype.is_air_inner_state
	 * @param isAirInnerState  the value for sys_worktype.is_air_inner_state
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public void setIsAirInnerState(Integer isAirInnerState) {
		this.isAirInnerState = isAirInnerState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_worktype.is_air_out
	 * @return  the value of sys_worktype.is_air_out
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public Boolean getIsAirOut() {
		return isAirOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_worktype.is_air_out
	 * @param isAirOut  the value for sys_worktype.is_air_out
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public void setIsAirOut(Boolean isAirOut) {
		this.isAirOut = isAirOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_worktype.is_air_out_state
	 * @return  the value of sys_worktype.is_air_out_state
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public Integer getIsAirOutState() {
		return isAirOutState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_worktype.is_air_out_state
	 * @param isAirOutState  the value for sys_worktype.is_air_out_state
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public void setIsAirOutState(Integer isAirOutState) {
		this.isAirOutState = isAirOutState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_worktype.sort
	 * @return  the value of sys_worktype.sort
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_worktype.sort
	 * @param sort  the value for sys_worktype.sort
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_worktype.valid
	 * @return  the value of sys_worktype.valid
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public Boolean getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_worktype.valid
	 * @param valid  the value for sys_worktype.valid
	 * @mbg.generated  Tue Nov 21 11:08:24 CST 2017
	 */
	public void setValid(Boolean valid) {
		this.valid = valid;
	}
}