package com.xhhxd.retail.bean.gd;

import java.math.BigDecimal;
import java.util.Date;

public class GdGoodStorageAdd {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_good_storage_add.id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_good_storage_add.good_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private String goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_good_storage_add.good_storage_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private String goodStorageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_good_storage_add.amount
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_good_storage_add.sale_price
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private BigDecimal salePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_good_storage_add.total_price
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_good_storage_add.remark
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_good_storage_add.create_user
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_good_storage_add.create_time
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_good_storage_add.id
     *
     * @return the value of gd_good_storage_add.id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_good_storage_add.id
     *
     * @param id the value for gd_good_storage_add.id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_good_storage_add.good_id
     *
     * @return the value of gd_good_storage_add.good_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public String getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_good_storage_add.good_id
     *
     * @param goodId the value for gd_good_storage_add.good_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setGoodId(String goodId) {
        this.goodId = goodId == null ? null : goodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_good_storage_add.good_storage_id
     *
     * @return the value of gd_good_storage_add.good_storage_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public String getGoodStorageId() {
        return goodStorageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_good_storage_add.good_storage_id
     *
     * @param goodStorageId the value for gd_good_storage_add.good_storage_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setGoodStorageId(String goodStorageId) {
        this.goodStorageId = goodStorageId == null ? null : goodStorageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_good_storage_add.amount
     *
     * @return the value of gd_good_storage_add.amount
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_good_storage_add.amount
     *
     * @param amount the value for gd_good_storage_add.amount
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_good_storage_add.sale_price
     *
     * @return the value of gd_good_storage_add.sale_price
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_good_storage_add.sale_price
     *
     * @param salePrice the value for gd_good_storage_add.sale_price
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_good_storage_add.total_price
     *
     * @return the value of gd_good_storage_add.total_price
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_good_storage_add.total_price
     *
     * @param totalPrice the value for gd_good_storage_add.total_price
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_good_storage_add.remark
     *
     * @return the value of gd_good_storage_add.remark
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_good_storage_add.remark
     *
     * @param remark the value for gd_good_storage_add.remark
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_good_storage_add.create_user
     *
     * @return the value of gd_good_storage_add.create_user
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_good_storage_add.create_user
     *
     * @param createUser the value for gd_good_storage_add.create_user
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_good_storage_add.create_time
     *
     * @return the value of gd_good_storage_add.create_time
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_good_storage_add.create_time
     *
     * @param createTime the value for gd_good_storage_add.create_time
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}