package com.xhhxd.retail.bean.gd;

import java.math.BigDecimal;

public class GdSaleGoodItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_sale_good_item.id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_sale_good_item.sale_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private String saleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_sale_good_item.good_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private String goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_sale_good_item.good_storage_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private String goodStorageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_sale_good_item.good_storage_add_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private String goodStorageAddId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_sale_good_item.amount
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_sale_good_item.sale_price
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private BigDecimal salePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_sale_good_item.total_price
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_sale_good_item.remark
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_sale_good_item.id
     *
     * @return the value of gd_sale_good_item.id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_sale_good_item.id
     *
     * @param id the value for gd_sale_good_item.id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_sale_good_item.sale_id
     *
     * @return the value of gd_sale_good_item.sale_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public String getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_sale_good_item.sale_id
     *
     * @param saleId the value for gd_sale_good_item.sale_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setSaleId(String saleId) {
        this.saleId = saleId == null ? null : saleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_sale_good_item.good_id
     *
     * @return the value of gd_sale_good_item.good_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public String getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_sale_good_item.good_id
     *
     * @param goodId the value for gd_sale_good_item.good_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setGoodId(String goodId) {
        this.goodId = goodId == null ? null : goodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_sale_good_item.good_storage_id
     *
     * @return the value of gd_sale_good_item.good_storage_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public String getGoodStorageId() {
        return goodStorageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_sale_good_item.good_storage_id
     *
     * @param goodStorageId the value for gd_sale_good_item.good_storage_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setGoodStorageId(String goodStorageId) {
        this.goodStorageId = goodStorageId == null ? null : goodStorageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_sale_good_item.good_storage_add_id
     *
     * @return the value of gd_sale_good_item.good_storage_add_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public String getGoodStorageAddId() {
        return goodStorageAddId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_sale_good_item.good_storage_add_id
     *
     * @param goodStorageAddId the value for gd_sale_good_item.good_storage_add_id
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setGoodStorageAddId(String goodStorageAddId) {
        this.goodStorageAddId = goodStorageAddId == null ? null : goodStorageAddId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_sale_good_item.amount
     *
     * @return the value of gd_sale_good_item.amount
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_sale_good_item.amount
     *
     * @param amount the value for gd_sale_good_item.amount
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_sale_good_item.sale_price
     *
     * @return the value of gd_sale_good_item.sale_price
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_sale_good_item.sale_price
     *
     * @param salePrice the value for gd_sale_good_item.sale_price
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_sale_good_item.total_price
     *
     * @return the value of gd_sale_good_item.total_price
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_sale_good_item.total_price
     *
     * @param totalPrice the value for gd_sale_good_item.total_price
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_sale_good_item.remark
     *
     * @return the value of gd_sale_good_item.remark
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_sale_good_item.remark
     *
     * @param remark the value for gd_sale_good_item.remark
     *
     * @mbg.generated Mon Jun 04 10:14:20 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}