package com.shiwulian.wechat.mapper.cs;

import com.shiwulian.wechat.bean.cs.CustomerCustomer;


public interface CustomerCustomerMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_customer_customer
	 * @mbg.generated  Thu Nov 02 11:48:18 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_customer_customer
	 * @mbg.generated  Thu Nov 02 11:48:18 CST 2017
	 */
	int insert(CustomerCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_customer_customer
	 * @mbg.generated  Thu Nov 02 11:48:18 CST 2017
	 */
	int insertSelective(CustomerCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_customer_customer
	 * @mbg.generated  Thu Nov 02 11:48:18 CST 2017
	 */
	CustomerCustomer selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_customer_customer
	 * @mbg.generated  Thu Nov 02 11:48:18 CST 2017
	 */
	int updateByPrimaryKeySelective(CustomerCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_customer_customer
	 * @mbg.generated  Thu Nov 02 11:48:18 CST 2017
	 */
	int updateByPrimaryKey(CustomerCustomer record);
	/**
	 * 修改客户 的[自我冗余:客户客户]
	 * isSelf : true 本司  自我冗余
	 */
	int updateIsSelfSelective(CustomerCustomer record);
}