package com.xhhxd.retail.bean.so;

public class SoPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_permission.id
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_permission.permission_name
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_permission.permission_sign
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    private String permissionSign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column so_permission.description
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_permission.id
     *
     * @return the value of so_permission.id
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_permission.id
     *
     * @param id the value for so_permission.id
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_permission.permission_name
     *
     * @return the value of so_permission.permission_name
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_permission.permission_name
     *
     * @param permissionName the value for so_permission.permission_name
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_permission.permission_sign
     *
     * @return the value of so_permission.permission_sign
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    public String getPermissionSign() {
        return permissionSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_permission.permission_sign
     *
     * @param permissionSign the value for so_permission.permission_sign
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    public void setPermissionSign(String permissionSign) {
        this.permissionSign = permissionSign == null ? null : permissionSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column so_permission.description
     *
     * @return the value of so_permission.description
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column so_permission.description
     *
     * @param description the value for so_permission.description
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}