package com.shiwulian.wechat.mapper.sys;

import java.util.List;

import com.shiwulian.wechat.bean.sys.BillType;


public interface BillTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_billtype
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_billtype
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    int insert(BillType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_billtype
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    int insertSelective(BillType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_billtype
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    BillType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_billtype
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    int updateByPrimaryKeySelective(BillType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_billtype
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    int updateByPrimaryKey(BillType record);
    
    /**
     * 根据BillType的字段查询对应的集合
     * @param record 空则全查
     * @return
     */
    List<BillType> selectByBillType(BillType record);
    
    List<BillType> selectList(List<Integer> ids);
}