package com.shiwulian.wechat.mapper.sys;

import java.util.List;

import com.shiwulian.wechat.bean.sys.FileType;

public interface FileTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file_type
     *
     * @mbg.generated Wed Jan 03 13:35:44 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file_type
     *
     * @mbg.generated Wed Jan 03 13:35:44 CST 2018
     */
    int insert(FileType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file_type
     *
     * @mbg.generated Wed Jan 03 13:35:44 CST 2018
     */
    int insertSelective(FileType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file_type
     *
     * @mbg.generated Wed Jan 03 13:35:44 CST 2018
     */
    FileType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file_type
     *
     * @mbg.generated Wed Jan 03 13:35:44 CST 2018
     */
    int updateByPrimaryKeySelective(FileType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_file_type
     *
     * @mbg.generated Wed Jan 03 13:35:44 CST 2018
     */
    int updateByPrimaryKey(FileType record);
    
    List<FileType> selectList(List<String> ids);
}