package com.shiwulian.wechat.mapper.sys;

import com.shiwulian.wechat.bean.sys.SequenceNumbers;

public interface SequenceNumbersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequencenumbers
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequencenumbers
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    int insert(SequenceNumbers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequencenumbers
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    int insertSelective(SequenceNumbers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequencenumbers
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    SequenceNumbers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequencenumbers
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    int updateByPrimaryKeySelective(SequenceNumbers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequencenumbers
     *
     * @mbg.generated Tue Oct 10 10:44:33 CST 2017
     */
    int updateByPrimaryKey(SequenceNumbers record);
    
	String updateSequenceNumberByBiz(String value);

	int selectTime(String info);

	int countByBizScopeName(String info);
}