package com.shiwulian.wechat.mapper.sys;

import java.util.List;

import com.shiwulian.wechat.bean.sys.ServerType;

public interface ServerTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_server_type
     *
     * @mbg.generated Mon Jan 08 16:22:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_server_type
     *
     * @mbg.generated Mon Jan 08 16:22:52 CST 2018
     */
    int insert(ServerType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_server_type
     *
     * @mbg.generated Mon Jan 08 16:22:52 CST 2018
     */
    int insertSelective(ServerType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_server_type
     *
     * @mbg.generated Mon Jan 08 16:22:52 CST 2018
     */
    ServerType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_server_type
     *
     * @mbg.generated Mon Jan 08 16:22:52 CST 2018
     */
    int updateByPrimaryKeySelective(ServerType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_server_type
     *
     * @mbg.generated Mon Jan 08 16:22:52 CST 2018
     */
    int updateByPrimaryKey(ServerType record);
    
    List<ServerType> selectList(List<Integer> ids);
}