package com.shiwulian.wechat.mapper.sys;

import java.util.List;

import com.shiwulian.wechat.bean.sys.TradeTerm;

public interface TradeTermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_trade_term
     *
     * @mbg.generated Mon Jan 08 15:11:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_trade_term
     *
     * @mbg.generated Mon Jan 08 15:11:10 CST 2018
     */
    int insert(TradeTerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_trade_term
     *
     * @mbg.generated Mon Jan 08 15:11:10 CST 2018
     */
    int insertSelective(TradeTerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_trade_term
     *
     * @mbg.generated Mon Jan 08 15:11:10 CST 2018
     */
    TradeTerm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_trade_term
     *
     * @mbg.generated Mon Jan 08 15:11:10 CST 2018
     */
    int updateByPrimaryKeySelective(TradeTerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_trade_term
     *
     * @mbg.generated Mon Jan 08 15:11:10 CST 2018
     */
    int updateByPrimaryKey(TradeTerm record);
    
    List<TradeTerm> selectList();
}