package com.shiwulian.wechat.mapper.sys;

import java.util.List;

import com.shiwulian.wechat.bean.sys.Unit;

public interface UnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_unit
     *
     * @mbg.generated Mon Jan 08 15:05:18 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_unit
     *
     * @mbg.generated Mon Jan 08 15:05:18 CST 2018
     */
    int insert(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_unit
     *
     * @mbg.generated Mon Jan 08 15:05:18 CST 2018
     */
    int insertSelective(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_unit
     *
     * @mbg.generated Mon Jan 08 15:05:18 CST 2018
     */
    Unit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_unit
     *
     * @mbg.generated Mon Jan 08 15:05:18 CST 2018
     */
    int updateByPrimaryKeySelective(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_unit
     *
     * @mbg.generated Mon Jan 08 15:05:18 CST 2018
     */
    int updateByPrimaryKey(Unit record);
    
    List<Unit> selectList();
}