package com.xhhxd.retail.mapper.so;

import com.xhhxd.retail.bean.so.SoPermission;

public interface SoPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_permission
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_permission
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int insert(SoPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_permission
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int insertSelective(SoPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_permission
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    SoPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_permission
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int updateByPrimaryKeySelective(SoPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_permission
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int updateByPrimaryKey(SoPermission record);
}