package com.xhhxd.retail.mapper.so;

import com.xhhxd.retail.bean.so.SoRole;

public interface SoRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_role
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_role
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int insert(SoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_role
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int insertSelective(SoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_role
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    SoRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_role
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int updateByPrimaryKeySelective(SoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_role
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int updateByPrimaryKey(SoRole record);
}