package com.xhhxd.retail.mapper.so;

import com.xhhxd.retail.bean.so.SoRolePermission;

public interface SoRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_role_permission
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_role_permission
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int insert(SoRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_role_permission
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int insertSelective(SoRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_role_permission
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    SoRolePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_role_permission
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int updateByPrimaryKeySelective(SoRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_role_permission
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int updateByPrimaryKey(SoRolePermission record);
}