package com.xhhxd.retail.mapper.so;

import com.xhhxd.retail.bean.so.SoUserRole;

public interface SoUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_user_role
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_user_role
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int insert(SoUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_user_role
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int insertSelective(SoUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_user_role
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    SoUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_user_role
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int updateByPrimaryKeySelective(SoUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table so_user_role
     *
     * @mbg.generated Mon Jun 04 10:15:41 CST 2018
     */
    int updateByPrimaryKey(SoUserRole record);
}